
/////////////////////////////////////////////////////////////////////////////
/////EYE CONSTANTS /////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////

//blue
const int VFX_EYES_BLUE_HUMAN_MALE = 324;
const int VFX_EYES_BLUE_HUMAN_FEMALE = 325;
const int VFX_EYES_BLUE_DWARF_MALE = 326;
const int VFX_EYES_BLUE_DWARF_FEMALE = 327;
const int VFX_EYES_BLUE_ELF_MALE = 328;
const int VFX_EYES_BLUE_ELF_FEMALE = 329;
const int VFX_EYES_BLUE_GNOME_MALE = 330;
const int VFX_EYES_BLUE_GNOME_FEMALE = 331;
const int VFX_EYES_BLUE_HALFLING_MALE = 332;
const int VFX_EYES_BLUE_HALFLING_FEMALE = 333;
const int VFX_EYES_BLUE_HALFORC_MALE = 334;
const int VFX_EYES_BLUE_HALFORC_FEMALE = 335;


//RED
const int IPPVFX_HEAD_EYES_RED_HUMAN_MALE = 4678;
const int IPPVFX_HEAD_EYES_RED_HUMAN_FEMALE = 4708;
const int IPPVFX_HEAD_EYES_RED_DWARF_MALE = 4318;
const int IPPVFX_HEAD_EYES_RED_DWARF_FEMALE = 4348;
const int IPPVFX_HEAD_EYES_RED_ELF_MALE = 4378;
const int IPPVFX_HEAD_EYES_RED_ELF_FEMALE = 4408;
const int IPPVFX_HEAD_EYES_RED_GNOME_MALE = 4438;
const int IPPVFX_HEAD_EYES_RED_GNOME_FEMALE = 4468;
const int IPPVFX_HEAD_EYES_RED_HALFLING_MALE = 4498;
const int IPPVFX_HEAD_EYES_RED_HALFLING_FEMALE  = 4528;
const int IPPVFX_HEAD_EYES_RED_HALFORC_MALE = 4618;
const int IPPVFX_HEAD_EYES_RED_HALFORC_FEMALE = 4648;

//BLACK
const int IPPVFX_HEAD_EYES_BLACK_HUMAN_MALE = 4679;
const int IPPVFX_HEAD_EYES_BLACK_HUMAN_FEMALE = 4709;
const int IPPVFX_HEAD_EYES_BLACK_DWARF_MALE = 4319;
const int IPPVFX_HEAD_EYES_BLACK_DWARF_FEMALE = 4349;
const int IPPVFX_HEAD_EYES_BLACK_ELF_MALE = 4379;
const int IPPVFX_HEAD_EYES_BLACK_ELF_FEMALE = 4409;
const int IPPVFX_HEAD_EYES_BLACK_GNOME_MALE = 4439;
const int IPPVFX_HEAD_EYES_BLACK_GNOME_FEMALE = 4469;
const int IPPVFX_HEAD_EYES_BLACK_HALFLING_MALE = 4499;
const int IPPVFX_HEAD_EYES_BLACK_HALFLING_FEMALE  = 4529;
const int IPPVFX_HEAD_EYES_BLACK_HALFORC_MALE = 4619;
const int IPPVFX_HEAD_EYES_BLACK_HALFORC_FEMALE = 4649;


/////////////////////////////////////////////////////////////////////////////
/////HELMS CONSTANTS /////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////


//dwarf male
const int IPPVFX_HEAD_HELM_05_DWARF_MALE = 4300;
const int IPPVFX_HEAD_HELM_08_DWARF_MALE = 4301;
const int IPPVFX_HEAD_HELM_09_DWARF_MALE = 4302;
const int IPPVFX_HEAD_HELM_12_DWARF_MALE = 4303;
const int IPPVFX_HEAD_HELM_13_DWARF_MALE = 4304;
const int IPPVFX_HEAD_HELM_14_DWARF_MALE = 4305;
const int IPPVFX_HEAD_HELM_16_DWARF_MALE = 4306;
const int IPPVFX_HEAD_HELM_17_DWARF_MALE = 4307;
const int IPPVFX_HEAD_HELM_20_DWARF_MALE = 4308;
const int IPPVFX_HEAD_HELM_24_DWARF_MALE = 4309;
const int IPPVFX_HEAD_HELM_28_DWARF_MALE = 4310;
const int IPPVFX_HEAD_HELM_29_DWARF_MALE = 4311;
const int IPPVFX_HEAD_HELM_30_DWARF_MALE = 4312;
const int IPPVFX_HEAD_HELM_32_DWARF_MALE = 4313;


//dwarf female
const int IPPVFX_HEAD_HELM_05_DWARF_FEMALE = 4330;
const int IPPVFX_HEAD_HELM_08_DWARF_FEMALE = 4331;
const int IPPVFX_HEAD_HELM_09_DWARF_FEMALE = 4332;
const int IPPVFX_HEAD_HELM_12_DWARF_FEMALE = 4333;
const int IPPVFX_HEAD_HELM_13_DWARF_FEMALE = 4334;
const int IPPVFX_HEAD_HELM_14_DWARF_FEMALE = 4335;
const int IPPVFX_HEAD_HELM_16_DWARF_FEMALE = 4336;
const int IPPVFX_HEAD_HELM_17_DWARF_FEMALE = 4337;
const int IPPVFX_HEAD_HELM_20_DWARF_FEMALE = 4338;
const int IPPVFX_HEAD_HELM_24_DWARF_FEMALE = 4339;
const int IPPVFX_HEAD_HELM_28_DWARF_FEMALE = 4340;
const int IPPVFX_HEAD_HELM_29_DWARF_FEMALE = 4341;
const int IPPVFX_HEAD_HELM_30_DWARF_FEMALE = 4342;
const int IPPVFX_HEAD_HELM_32_DWARF_FEMALE = 4343;

//ELF male
const int IPPVFX_HEAD_HELM_05_ELF_MALE = 4360;
const int IPPVFX_HEAD_HELM_08_ELF_MALE = 4361;
const int IPPVFX_HEAD_HELM_09_ELF_MALE = 4362;
const int IPPVFX_HEAD_HELM_12_ELF_MALE = 4363;
const int IPPVFX_HEAD_HELM_13_ELF_MALE = 4364;
const int IPPVFX_HEAD_HELM_14_ELF_MALE = 4365;
const int IPPVFX_HEAD_HELM_16_ELF_MALE = 4366;
const int IPPVFX_HEAD_HELM_17_ELF_MALE = 4367;
const int IPPVFX_HEAD_HELM_20_ELF_MALE = 4368;
const int IPPVFX_HEAD_HELM_24_ELF_MALE = 4369;
const int IPPVFX_HEAD_HELM_28_ELF_MALE = 4370;
const int IPPVFX_HEAD_HELM_29_ELF_MALE = 4371;
const int IPPVFX_HEAD_HELM_30_ELF_MALE = 4372;
const int IPPVFX_HEAD_HELM_32_ELF_MALE = 4373;


//ELF female
const int IPPVFX_HEAD_HELM_05_ELF_FEMALE = 4390;
const int IPPVFX_HEAD_HELM_08_ELF_FEMALE = 4391;
const int IPPVFX_HEAD_HELM_09_ELF_FEMALE = 4392;
const int IPPVFX_HEAD_HELM_12_ELF_FEMALE = 4393;
const int IPPVFX_HEAD_HELM_13_ELF_FEMALE = 4394;
const int IPPVFX_HEAD_HELM_14_ELF_FEMALE = 4395;
const int IPPVFX_HEAD_HELM_16_ELF_FEMALE = 4396;
const int IPPVFX_HEAD_HELM_17_ELF_FEMALE = 4397;
const int IPPVFX_HEAD_HELM_20_ELF_FEMALE = 4398;
const int IPPVFX_HEAD_HELM_24_ELF_FEMALE = 4399;
const int IPPVFX_HEAD_HELM_28_ELF_FEMALE = 4400;
const int IPPVFX_HEAD_HELM_29_ELF_FEMALE = 4401;
const int IPPVFX_HEAD_HELM_30_ELF_FEMALE = 4402;
const int IPPVFX_HEAD_HELM_32_ELF_FEMALE = 4403;


//GNOME male
const int IPPVFX_HEAD_HELM_05_GNOME_MALE = 4420;
const int IPPVFX_HEAD_HELM_08_GNOME_MALE = 4421;
const int IPPVFX_HEAD_HELM_09_GNOME_MALE = 4422;
const int IPPVFX_HEAD_HELM_12_GNOME_MALE = 4423;
const int IPPVFX_HEAD_HELM_13_GNOME_MALE = 4424;
const int IPPVFX_HEAD_HELM_14_GNOME_MALE = 4425;
const int IPPVFX_HEAD_HELM_16_GNOME_MALE = 4426;
const int IPPVFX_HEAD_HELM_17_GNOME_MALE = 4427;
const int IPPVFX_HEAD_HELM_20_GNOME_MALE = 4428;
const int IPPVFX_HEAD_HELM_24_GNOME_MALE = 4429;
const int IPPVFX_HEAD_HELM_28_GNOME_MALE = 4430;
const int IPPVFX_HEAD_HELM_29_GNOME_MALE = 4431;
const int IPPVFX_HEAD_HELM_30_GNOME_MALE = 4432;
const int IPPVFX_HEAD_HELM_32_GNOME_MALE = 4433;


//GNOME female
const int IPPVFX_HEAD_HELM_05_GNOME_FEMALE = 4450;
const int IPPVFX_HEAD_HELM_08_GNOME_FEMALE = 4451;
const int IPPVFX_HEAD_HELM_09_GNOME_FEMALE = 4452;
const int IPPVFX_HEAD_HELM_12_GNOME_FEMALE = 4453;
const int IPPVFX_HEAD_HELM_13_GNOME_FEMALE = 4454;
const int IPPVFX_HEAD_HELM_14_GNOME_FEMALE = 4455;
const int IPPVFX_HEAD_HELM_16_GNOME_FEMALE = 4456;
const int IPPVFX_HEAD_HELM_17_GNOME_FEMALE = 4457;
const int IPPVFX_HEAD_HELM_20_GNOME_FEMALE = 4458;
const int IPPVFX_HEAD_HELM_24_GNOME_FEMALE = 4459;
const int IPPVFX_HEAD_HELM_28_GNOME_FEMALE = 4460;
const int IPPVFX_HEAD_HELM_29_GNOME_FEMALE = 4461;
const int IPPVFX_HEAD_HELM_30_GNOME_FEMALE = 4462;
const int IPPVFX_HEAD_HELM_32_GNOME_FEMALE = 4463;

//HALFING  male
const int IPPVFX_HEAD_HELM_05_HALFLING_MALE = 4480;
const int IPPVFX_HEAD_HELM_08_HALFLING_MALE = 4481;
const int IPPVFX_HEAD_HELM_09_HALFLING_MALE = 4482;
const int IPPVFX_HEAD_HELM_12_HALFLING_MALE = 4483;
const int IPPVFX_HEAD_HELM_13_HALFLING_MALE = 4484;
const int IPPVFX_HEAD_HELM_14_HALFLING_MALE = 4485;
const int IPPVFX_HEAD_HELM_16_HALFLING_MALE = 4486;
const int IPPVFX_HEAD_HELM_17_HALFLING_MALE = 4487;
const int IPPVFX_HEAD_HELM_20_HALFLING_MALE = 4488;
const int IPPVFX_HEAD_HELM_24_HALFLING_MALE = 4489;
const int IPPVFX_HEAD_HELM_28_HALFLING_MALE = 4490;
const int IPPVFX_HEAD_HELM_29_HALFLING_MALE = 4491;
const int IPPVFX_HEAD_HELM_30_HALFLING_MALE = 4492;
const int IPPVFX_HEAD_HELM_32_HALFLING_MALE = 4493;


//HALFING  female
const int IPPVFX_HEAD_HELM_05_HALFLING_FEMALE = 4510;
const int IPPVFX_HEAD_HELM_08_HALFLING_FEMALE = 4511;
const int IPPVFX_HEAD_HELM_09_HALFLING_FEMALE = 4512;
const int IPPVFX_HEAD_HELM_12_HALFLING_FEMALE = 4513;
const int IPPVFX_HEAD_HELM_13_HALFLING_FEMALE = 4514;
const int IPPVFX_HEAD_HELM_14_HALFLING_FEMALE = 4515;
const int IPPVFX_HEAD_HELM_16_HALFLING_FEMALE = 4516;
const int IPPVFX_HEAD_HELM_17_HALFLING_FEMALE = 4517;
const int IPPVFX_HEAD_HELM_20_HALFLING_FEMALE = 4518;
const int IPPVFX_HEAD_HELM_24_HALFLING_FEMALE = 4519;
const int IPPVFX_HEAD_HELM_28_HALFLING_FEMALE = 4520;
const int IPPVFX_HEAD_HELM_29_HALFLING_FEMALE = 4521;
const int IPPVFX_HEAD_HELM_30_HALFLING_FEMALE = 4522;
const int IPPVFX_HEAD_HELM_32_HALFLING_FEMALE = 4523;


//HALFORC  male
const int IPPVFX_HEAD_HELM_05_HALFORC_MALE = 4600;
const int IPPVFX_HEAD_HELM_08_HALFORC_MALE = 4601;
const int IPPVFX_HEAD_HELM_09_HALFORC_MALE = 4602;
const int IPPVFX_HEAD_HELM_12_HALFORC_MALE = 4603;
const int IPPVFX_HEAD_HELM_13_HALFORC_MALE = 4604;
const int IPPVFX_HEAD_HELM_14_HALFORC_MALE = 4605;
const int IPPVFX_HEAD_HELM_16_HALFORC_MALE = 4606;
const int IPPVFX_HEAD_HELM_17_HALFORC_MALE = 4607;
const int IPPVFX_HEAD_HELM_20_HALFORC_MALE = 4608;
const int IPPVFX_HEAD_HELM_24_HALFORC_MALE = 4609;
const int IPPVFX_HEAD_HELM_28_HALFORC_MALE = 4610;
const int IPPVFX_HEAD_HELM_29_HALFORC_MALE = 4611;
const int IPPVFX_HEAD_HELM_30_HALFORC_MALE = 4612;
const int IPPVFX_HEAD_HELM_32_HALFORC_MALE = 4613;


//HALFORC  female
const int IPPVFX_HEAD_HELM_05_HALFORC_FEMALE = 4630;
const int IPPVFX_HEAD_HELM_08_HALFORC_FEMALE = 4631;
const int IPPVFX_HEAD_HELM_09_HALFORC_FEMALE = 4632;
const int IPPVFX_HEAD_HELM_12_HALFORC_FEMALE = 4633;
const int IPPVFX_HEAD_HELM_13_HALFORC_FEMALE = 4634;
const int IPPVFX_HEAD_HELM_14_HALFORC_FEMALE = 4635;
const int IPPVFX_HEAD_HELM_16_HALFORC_FEMALE = 4636;
const int IPPVFX_HEAD_HELM_17_HALFORC_FEMALE = 4637;
const int IPPVFX_HEAD_HELM_20_HALFORC_FEMALE = 4638;
const int IPPVFX_HEAD_HELM_24_HALFORC_FEMALE = 4639;
const int IPPVFX_HEAD_HELM_28_HALFORC_FEMALE = 4640;
const int IPPVFX_HEAD_HELM_29_HALFORC_FEMALE = 4641;
const int IPPVFX_HEAD_HELM_30_HALFORC_FEMALE = 4642;
const int IPPVFX_HEAD_HELM_32_HALFORC_FEMALE = 4643;

//HUMAN  male
const int IPPVFX_HEAD_HELM_05_HUMAN_MALE = 4660;
const int IPPVFX_HEAD_HELM_08_HUMAN_MALE = 4661;
const int IPPVFX_HEAD_HELM_09_HUMAN_MALE = 4662;
const int IPPVFX_HEAD_HELM_12_HUMAN_MALE = 4663;
const int IPPVFX_HEAD_HELM_13_HUMAN_MALE = 4664;
const int IPPVFX_HEAD_HELM_14_HUMAN_MALE = 4665;
const int IPPVFX_HEAD_HELM_16_HUMAN_MALE = 4666;
const int IPPVFX_HEAD_HELM_17_HUMAN_MALE = 4667;
const int IPPVFX_HEAD_HELM_20_HUMAN_MALE = 4668;
const int IPPVFX_HEAD_HELM_24_HUMAN_MALE = 4669;
const int IPPVFX_HEAD_HELM_28_HUMAN_MALE = 4670;
const int IPPVFX_HEAD_HELM_29_HUMAN_MALE = 4671;
const int IPPVFX_HEAD_HELM_30_HUMAN_MALE = 4672;
const int IPPVFX_HEAD_HELM_32_HUMAN_MALE = 4673;


//HALFORC  female
const int IPPVFX_HEAD_HELM_05_HUMAN_FEMALE = 4690;
const int IPPVFX_HEAD_HELM_08_HUMAN_FEMALE = 4691;
const int IPPVFX_HEAD_HELM_09_HUMAN_FEMALE = 4692;
const int IPPVFX_HEAD_HELM_12_HUMAN_FEMALE = 4693;
const int IPPVFX_HEAD_HELM_13_HUMAN_FEMALE = 4694;
const int IPPVFX_HEAD_HELM_14_HUMAN_FEMALE = 4695;
const int IPPVFX_HEAD_HELM_16_HUMAN_FEMALE = 4696;
const int IPPVFX_HEAD_HELM_17_HUMAN_FEMALE = 4697;
const int IPPVFX_HEAD_HELM_20_HUMAN_FEMALE = 4698;
const int IPPVFX_HEAD_HELM_24_HUMAN_FEMALE = 4699;
const int IPPVFX_HEAD_HELM_28_HUMAN_FEMALE = 4700;
const int IPPVFX_HEAD_HELM_29_HUMAN_FEMALE = 4701;
const int IPPVFX_HEAD_HELM_30_HUMAN_FEMALE = 4702;
const int IPPVFX_HEAD_HELM_32_HUMAN_FEMALE = 4703;


/////////////////////////////////////////////////////////////////////////////
/////HORNS CONSTANTS /////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////

//DWARF male
const int IPPVFX_HEAD_HORNS_MEPH_DWARF_MALE = 4320;
const int IPPVFX_HEAD_HORNS_OX_DWARF_MALE = 4321;
const int IPPVFX_HEAD_HORNS_ROTHE_DWARF_MALE = 4322;
const int IPPVFX_HEAD_HORNS_BALOR_DWARF_MALE = 4323;
const int IPPVFX_HEAD_HORNS_DRAGON_DWARF_MALE = 4324;
const int IPPVFX_HEAD_HORNS_RAM_DWARF_MALE = 4325;
const int IPPVFX_HEAD_ANTLERS_DWARF_MALE = 4326;
const int VFX_HORN_DEMON_1_DWARF_MALE_AENE = 6157;

//DWARF female
const int IPPVFX_HEAD_HORNS_MEPH_DWARF_FEMALE = 4350;
const int IPPVFX_HEAD_HORNS_OX_DWARF_FEMALE = 4351;
const int IPPVFX_HEAD_HORNS_ROTHE_DWARF_FEMALE = 4352;
const int IPPVFX_HEAD_HORNS_BALOR_DWARF_FEMALE = 4353;
const int IPPVFX_HEAD_HORNS_DRAGON_DWARF_FEMALE = 4354;
const int IPPVFX_HEAD_HORNS_RAM_DWARF_FEMALE = 4355;
const int IPPVFX_HEAD_ANTLERS_DWARF_FEMALE = 4356;
const int VFX_HORN_DEMON_1_DWARF_FEMALE_AENE = 6156;

//ELF male
const int IPPVFX_HEAD_HORNS_MEPH_ELF_MALE = 4380;
const int IPPVFX_HEAD_HORNS_OX_ELF_MALE = 4381;
const int IPPVFX_HEAD_HORNS_ROTHE_ELF_MALE = 4382;
const int IPPVFX_HEAD_HORNS_BALOR_ELF_MALE = 4383;
const int IPPVFX_HEAD_HORNS_DRAGON_ELF_MALE = 4384;
const int IPPVFX_HEAD_HORNS_RAM_ELF_MALE = 4385;
const int IPPVFX_HEAD_ANTLERS_ELF_MALE = 4386;
const int VFX_HORN_DEMON_1_ELF_MALE_AENE = 6159;

//ELF female
const int IPPVFX_HEAD_HORNS_MEPH_ELF_FEMALE = 4410;
const int IPPVFX_HEAD_HORNS_OX_ELF_FEMALE = 4411;
const int IPPVFX_HEAD_HORNS_ROTHE_ELF_FEMALE = 4412;
const int IPPVFX_HEAD_HORNS_BALOR_ELF_FEMALE = 4413;
const int IPPVFX_HEAD_HORNS_DRAGON_ELF_FEMALE = 4414;
const int IPPVFX_HEAD_HORNS_RAM_ELF_FEMALE = 4415;
const int IPPVFX_HEAD_ANTLERS_ELF_FEMALE = 4416;
const int VFX_HORN_DEMON_1_ELF_FEMALE_AENE = 6158;

//GNOME male
const int IPPVFX_HEAD_HORNS_MEPH_GNOME_MALE = 4440;
const int IPPVFX_HEAD_HORNS_OX_GNOME_MALE = 4441;
const int IPPVFX_HEAD_HORNS_ROTHE_GNOME_MALE = 4442;
const int IPPVFX_HEAD_HORNS_BALOR_GNOME_MALE = 4443;
const int IPPVFX_HEAD_HORNS_DRAGON_GNOME_MALE = 4444;
const int IPPVFX_HEAD_HORNS_RAM_GNOME_MALE = 4445;
const int IPPVFX_HEAD_ANTLERS_GNOME_MALE = 4446;
const int VFX_HORN_DEMON_1_GNOME_MALE_AENE = 6163;

//GNOME female
const int IPPVFX_HEAD_HORNS_MEPH_GNOME_FEMALE = 4470;
const int IPPVFX_HEAD_HORNS_OX_GNOME_FEMALE = 4471;
const int IPPVFX_HEAD_HORNS_ROTHE_GNOME_FEMALE = 4472;
const int IPPVFX_HEAD_HORNS_BALOR_GNOME_FEMALE = 4473;
const int IPPVFX_HEAD_HORNS_DRAGON_GNOME_FEMALE = 4474;
const int IPPVFX_HEAD_HORNS_RAM_GNOME_FEMALE = 4475;
const int IPPVFX_HEAD_ANTLERS_GNOME_FEMALE = 4476;
const int VFX_HORN_DEMON_1_GNOME_FEMALE_AENE = 6162;

//HALFLING male
const int IPPVFX_HEAD_HORNS_MEPH_HALFLING_MALE = 4500;
const int IPPVFX_HEAD_HORNS_OX_HALFLING_MALE = 4501;
const int IPPVFX_HEAD_HORNS_ROTHE_HALFLING_MALE = 4502;
const int IPPVFX_HEAD_HORNS_BALOR_HALFLING_MALE = 4503;
const int IPPVFX_HEAD_HORNS_DRAGON_HALFLING_MALE = 4504;
const int IPPVFX_HEAD_HORNS_RAM_HALFLING_MALE = 4505;
const int IPPVFX_HEAD_ANTLERS_HALFLING_MALE = 4506;
const int VFX_HORN_DEMON_1_HALFLING_MALE_AENE = 6161;

//HALFLING female
const int IPPVFX_HEAD_HORNS_MEPH_HALFLING_FEMALE = 4530;
const int IPPVFX_HEAD_HORNS_OX_HALFLING_FEMALE = 4531;
const int IPPVFX_HEAD_HORNS_ROTHE_HALFLING_FEMALE = 4532;
const int IPPVFX_HEAD_HORNS_BALOR_HALFLING_FEMALE = 4533;
const int IPPVFX_HEAD_HORNS_DRAGON_HALFLING_FEMALE = 4534;
const int IPPVFX_HEAD_HORNS_RAM_HALFLING_FEMALE = 4535;
const int IPPVFX_HEAD_ANTLERS_HALFLING_FEMALE = 4536;
const int VFX_HORN_DEMON_1_HALFLING_FEMALE_AENE = 6160;

//HALFORC male
const int IPPVFX_HEAD_HORNS_MEPH_HALFORC_MALE = 4620;
const int IPPVFX_HEAD_HORNS_OX_HALFORC_MALE = 4621;
const int IPPVFX_HEAD_HORNS_ROTHE_HALFORC_MALE = 4622;
const int IPPVFX_HEAD_HORNS_BALOR_HALFORC_MALE = 4623;
const int IPPVFX_HEAD_HORNS_DRAGON_HALFORC_MALE = 4624;
const int IPPVFX_HEAD_HORNS_RAM_HALFORC_MALE = 4625;
const int IPPVFX_HEAD_ANTLERS_HALFORC_MALE = 4626;
const int VFX_HORN_DEMON_1_HALFORC_MALE_AENE = 6167;

//HALFORC female
const int IPPVFX_HEAD_HORNS_MEPH_HALFORC_FEMALE = 4650;
const int IPPVFX_HEAD_HORNS_OX_HALFORC_FEMALE = 4651;
const int IPPVFX_HEAD_HORNS_ROTHE_HALFORC_FEMALE = 4652;
const int IPPVFX_HEAD_HORNS_BALOR_HALFORC_FEMALE = 4653;
const int IPPVFX_HEAD_HORNS_DRAGON_HALFORC_FEMALE = 4654;
const int IPPVFX_HEAD_HORNS_RAM_HALFORC_FEMALE = 4655;
const int IPPVFX_HEAD_ANTLERS_HALFORC_FEMALE = 4656;
const int VFX_HORN_DEMON_1_HALFORC_FEMALE_AENE = 6166;

//HUMAN male
const int IPPVFX_HEAD_HORNS_MEPH_HUMAN_MALE = 4680;
const int IPPVFX_HEAD_HORNS_OX_HUMAN_MALE = 4681;
const int IPPVFX_HEAD_HORNS_ROTHE_HUMAN_MALE = 4682;
const int IPPVFX_HEAD_HORNS_BALOR_HUMAN_MALE = 4683;
const int IPPVFX_HEAD_HORNS_DRAGON_HUMAN_MALE = 4684;
const int IPPVFX_HEAD_HORNS_RAM_HUMAN_MALE = 4685;
const int IPPVFX_HEAD_ANTLERS_HUMAN_MALE = 4686;
const int VFX_HORN_DEMON_1_HUMAN_MALE_AENE = 6165;

//HUMAN female
const int IPPVFX_HEAD_HORNS_MEPH_HUMAN_FEMALE = 4710;
const int IPPVFX_HEAD_HORNS_OX_HUMAN_FEMALE = 4711;
const int IPPVFX_HEAD_HORNS_ROTHE_HUMAN_FEMALE = 4712;
const int IPPVFX_HEAD_HORNS_BALOR_HUMAN_FEMALE = 4713;
const int IPPVFX_HEAD_HORNS_DRAGON_HUMAN_FEMALE = 4714;
const int IPPVFX_HEAD_HORNS_RAM_HUMAN_FEMALE = 4715;
const int IPPVFX_HEAD_ANTLERS_HUMAN_FEMALE = 4716;
const int VFX_HORN_DEMON_1_HUMAN_FEMALE_AENE = 6164;

/////////////////////////////////////////////////////////////////////////////
/////HAIR CONSTANTS /////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////

//Fire hair
const int VFX_HAIR_FIRE_O_DWARF_MALE_AENEA = 6145;
const int VFX_HAIR_FIRE_O_DWARF_FEMALE_AENEA = 6144;
const int VFX_HAIR_FIRE_O_ELF_MALE_AENEA = 6147;
const int VFX_HAIR_FIRE_O_ELF_FEMALE_AENEA = 6146;
const int VFX_HAIR_FIRE_O_GNOME_MALE_AENEA = 6151;
const int VFX_HAIR_FIRE_O_GNOME_FEMALE_AENEA = 6150;
const int VFX_HAIR_FIRE_O_HALFLING_MALE_AENEA = 6149;
const int VFX_HAIR_FIRE_O_HALFLING_FEMALE_AENEA = 6148;
const int VFX_HAIR_FIRE_O_HALFORC_MALE_AENEA = 6155;
const int VFX_HAIR_FIRE_O_HALFORC_FEMALE_AENEA = 6154;
const int VFX_HAIR_FIRE_O_HUMAN_MALE_AENEA = 6153;
const int VFX_HAIR_FIRE_O_HUMAN_FEMALE_AENEA = 6152;
