/////////////////////////////////////////////////
///////// CONSTANTES PERSONALIZADAS PDB /////////
/////////////////////////////////////////////////

// CLASES
const int CLASS_TYPE_CABALLERO_PROTECTOR = 41;
const int CLASS_TYPE_TIRADOR_ESPESURA    = 42;
const int CLASS_TYPE_BRIBON_ARCANO       = 43;
const int CLASS_TYPE_LADRON_SOMBRAS_AMN  = 44;
const int CLASS_TYPE_CABALLERO_ARCANO    = 45;
const int CLASS_TYPE_SHADOW_ADEPT        = 46;
const int CLASS_TYPE_ORCUS               = 47;
const int CLASS_TYPE_TEURGO_MIST         = 48;
const int CLASS_TYPE_SOLDIER_OF_LIGHT    = 50;
const int CLASS_TYPE_BLIGHTER            = 51;
const int CLASS_TYPE_ARCHMAGE            = 53;
const int CLASS_TYPE_HARPER_DIVINE       = 54;
const int CLASS_TYPE_SHADOW_ADEPT_DIVINE = 55;
const int CLASS_TYPE_BERSERKER           = 56;
const int CLASS_TYPE_WARLOCK             = 57;
const int CLASS_TYPE_FAVORED_SOUL        = 59;
const int CLASS_TYPE_PAL_ANTIGUO         = 60;
const int CLASS_TYPE_PAL_OSCURO          = 61;
const int CLASS_TYPE_PAL_VENGADOR        = 62;
const int CLASS_TYPE_MAESTRO_FORMAS      = 63;
const int CLASS_TYPE_INGENIERO           = 64;


// RAZAS
const int RACIAL_TYPE_FORTECOR = 160;
const int RACIAL_TYPE_WOOD_ELF = 161;
const int RACIAL_TYPE_WIGHT = 162;
const int RACIAL_TYPE_SOLAR_ELF = 163;
const int RACIAL_TYPE_DROW_BASICO = 164;
const int RACIAL_TYPE_SEMIELFO2 = 165;
const int RACIAL_TYPE_DWARF_DORADO = 166;
const int RACIAL_TYPE_GNOLL = 167;
const int RACIAL_TYPE_GRAN_TRASGO = 168;
const int RACIAL_TYPE_KOBOLD = 169;
const int RACIAL_TYPE_ORCO_MONTANA = 170;
const int RACIAL_TYPE_SEMIOGRO = 171;
const int RACIAL_TYPE_TRASGO = 172;
const int RACIAL_TYPE_DUERGAR = 173;
const int RACIAL_TYPE_TIEFLING = 174;
const int RACIAL_TYPE_DRACONIDO = 175;

const int RACIAL_TYPE_FEYRI = 180;
const int RACIAL_TYPE_KENKU = 181;
const int RACIAL_TYPE_CELADRIN = 182;
const int RACIAL_TYPE_AZERBLOOD = 183;
const int RACIAL_TYPE_AASIMAR = 184;
const int RACIAL_TYPE_DWARF_ARTICO = 185;
const int RACIAL_TYPE_ESTRELLAS_ELF = 186;
const int RACIAL_TYPE_SALVAJE_ELF = 187;
const int RACIAL_TYPE_GAGUA = 188;
const int RACIAL_TYPE_GAIRE = 189;
const int RACIAL_TYPE_GFUEGO = 190;
const int RACIAL_TYPE_GTIERRA = 191;
const int RACIAL_TYPE_AVARIEL = 192;
const int RACIAL_TYPE_OSGO = 193;
const int RACIAL_TYPE_GOLIAT = 194;
const int RACIAL_TYPE_SHADARKAI = 195;

const int RACIAL_TYPE_TANARUKK = 220;
const int RACIAL_TYPE_GITHZERAI = 221;
const int RACIAL_TYPE_DROW = 222;
const int RACIAL_TYPE_OGRO = 223;
const int RACIAL_TYPE_MINOTAURO = 224;
const int RACIAL_TYPE_YUANTI = 225;

const int RACIAL_TYPE_OGROHECHICERO = 240;

// PLANTILLAS
const int FEAT_TEMPLATE_VAMPIRE_SPAWN = 1563;

// HABILIDADES
const int SKILL_SENSE_MOTIVE        = 28;
const int SKILL_DECIPHER_SCRIPT     = 29;
const int SKILL_DISGUISE            = 30;
const int SKILL_BALANCE             = 31;
const int SKILL_ESCAPE_ARTIST       = 32;
const int SKILL_FORGERY             = 33;
const int SKILL_SPEAK_LANGUAGE      = 34;
const int SKILL_GATHER_INFORMATION  = 35;
const int SKILL_SURVIVAL            = 36;
const int SKILL_CLIMB               = 37;
const int SKILL_USE_ROPE            = 38;

// DOTES
const int FEAT_SHADOWWEAVE          = 1354;
const int FEAT_CONJUROS_VETERANO    = 1369;
const int FEAT_MASTERY_SHAPES       = 1425;
const int FEAT_SPELL_POWER_I        = 1426;
const int FEAT_SPELL_POWER_II       = 1427;
const int FEAT_SPELL_POWER_III      = 1428;
const int FEAT_SPELL_POWER_IV       = 1429;
const int FEAT_SPELL_POWER_V        = 1430;
const int FEAT_ARCANE_FIRE          = 1431;
const int FEAT_SPELL_LIKE           = 1432;
const int FEAT_EPIC_WARLOCK_EXPLOSION_1 = 1516;
const int FEAT_EPIC_WARLOCK_EXPLOSION_2 = 1517;
const int FEAT_EPIC_WARLOCK_EXPLOSION_3 = 1518;
const int FEAT_EPIC_WARLOCK_EXPLOSION_4 = 1519;
const int FEAT_SKILL_AFFINITY_BLUFF = 1523;
const int FEAT_SKILL_AFFINITY_HIDE = 1524;
const int FEAT_APTDEM_TS_LIGHTNING = 1525;
const int FEAT_APTDEM_TS_POISON = 1526;
const int FEAT_APTDEM_FIRE_RESISTANCE = 1527;
const int FEAT_APTDEM_DAMAGE_RESISTANCE = 1528;
const int FEAT_APTDEM_CHARM_PERSON = 1529;
const int FEAT_APTDEM_CLAIRVOYANCE = 1530;
const int FEAT_APTDEM_ENERVATION = 1531;
const int FEAT_APTDEM_DARKNESS = 1532;
const int FEAT_APTDEM_DIMENSION_DOOR = 1533;
const int FEAT_APTDEM_SUGGESTION = 1534;
const int FEAT_APTRAC_ALTER_ASPECT = 1535;
const int FEAT_SKILL_AFFINITY_PERFORM = 1536;
const int FEAT_MELODIOUS_VOICE = 1537;
const int FEAT_SKILL_AFFINITY_APPRAISE = 1538;
const int FEAT_SKILL_AFFINITY_CRAFTING = 1539;
const int FEAT_SKILL_AFFINITY_GATHER_INFORMATION = 1540;
const int FEAT_SKILL_AFFINITY_PERSUADE = 1541;
const int FEAT_FAVORED_SOUL_COLD_RESISTANCE = 1542;
const int FEAT_FAVORED_SOUL_ACID_RESISTANCE = 1543;
const int FEAT_FAVORED_SOUL_FIRE_RESISTANCE = 1544;
const int FEAT_FAVORED_SOUL_ELECTRICAL_RESISTANCE = 1545;
const int FEAT_FAVORED_SOUL_SONIC_RESISTANCE = 1546;
const int FEAT_FAVORED_SOUL_DAMAGE_RESISTANCE = 1547;
const int FEAT_FAVORED_SOUL_WINGS = 1548;
const int FEAT_FAVORED_SOUL_SPECIALIZATION = 1549;
const int FEAT_MDL_AFINIDAD10 = 1551;
const int FEAT_MDL_AFINIDAD20 = 1552;
const int FEAT_MDL_VIGOR = 1553;
const int FEAT_MDL_HUESOS = 1554;
const int FEAT_MDL_MAESTRIA = 1556;

// ÁREAS DE EFECTO
const int AOE_PER_WARLOCK_WALLFIRE = 65;
const int AOE_PER_ING_HUMIFICADOR = 67;
const int AOE_PER_ING_BOMBARAICES = 68;
const int AOE_PER_ING_BOMBAGAS = 69;
const int AOE_PER_ING_FUEGOALQUIMISTA = 70;

// NUEVOS DAÑOS Y SUS INMUNIDADES
const int DAMAGE_TYPE_FUERZA = DAMAGE_TYPE_CUSTOM2;
const int DAMAGE_TYPE_VENENO = DAMAGE_TYPE_CUSTOM3;
const int DAMAGE_TYPE_PSIQUICO = DAMAGE_TYPE_CUSTOM4;
const int IP_CONST_DAMAGETYPE_FUERZA = 16;
const int IP_CONST_DAMAGETYPE_VENENO = 17;
const int IP_CONST_DAMAGETYPE_PSIQUICO = 18;

// EFECTO VISUAL DE CUANDO SE ESTÁ ESCRIBIENDO EN EL CHAT.
const int VFX_DUR_CHAT_BUBBLE = 8202;


