#include "nw_o0_itemmaker"

const int NUM_DIST_INGRED = 350; // Numero de ingredientes distintos

// Cada vez que se incluya un ingrediente deben crearse tres lineas (etiqueta, variable y nombre)
// El numero debe ser el siguiente libre y actualizarse la constante de arriba

void CargaArray(object oUbicado)
{
  SetLocalArrayString(oUbicado, "sTagIngOficio", 1, "NW_IT_MSMLMISC08");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 1, "NW_IT_MSMLMISC08");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 1, "Abdómenes de escarabajo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 2, "AceiteSigilo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 2, "AceiteSigilo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 2, "Aceites de oliva: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 3, "sute_her_DM1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 3, "sute_her_DM1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 3, "Aguas puras: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 4, "pb_artesa_muni");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 4, "pb_artesa_muni");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 4, "Aletas de locathah: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 5, "pb_artesa_sal201");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 5, "pb_artesa_sal201");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 5, "Aleteos de sagifalco juvenil: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 6, "pb_artesa_hab32");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 6, "pb_artesa_hab32");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 6, "Antenas de grilio: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 7, "ardorDesertico");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 7, "ardordesertico");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 7, "Ardores desérticos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 8, "pb_artesa_lim02");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 8, "pb_artesa_lim02");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 8, "Armazones de siv: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 9, "pb_artesa_car3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 9, "pb_artesa_car3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 9, "Astucia de arpía: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 10, "pb_artesa_hab28");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 10, "pb_artesa_hab28");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 10, "Astucia de márilith: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 11, "bayaAcuosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 11, "bayaacuosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 11, "Bayas acuosas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 12, "NW_IT_MSMLMISC23");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 12, "NW_IT_MSMLMISC23");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 12, "Belladonas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 13, "pb_artesa_hab00");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 13, "pb_artesa_hab00");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 13, "Bellezas cegadoras de ninfa: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 14, "pb_artesa_inconj");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 14, "pb_artesa_inconj");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 14, "Bellezas sobrenaturales de clangarconte: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 15, "pb_artesa_hab21");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 15, "pb_artesa_hab21");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 15, "Bolsas viscosas de bestia del caos: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 16, "pb_artesa_rc");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 16, "pb_artesa_rc");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 16, "Brasas de Azer: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 17, "brisaSusurrante");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 17, "brisasusurrante");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 17, "Brisas susurrantes: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 18, "pb_artesa_sal209");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 18, "pb_artesa_sal209");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 18, "Brillos de magmino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 19, "pb_artesa_hab03");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 19, "pb_artesa_hab03");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 19, "Cabellos de ghaele: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 20, "pb_artesa_hab22");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 20, "pb_artesa_hab22");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 20, "Cadenas de kiton: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 21, "pb_artesa_sal205");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 21, "pb_artesa_sal205");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 21, "Calimas de zombi de bruma tirana: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 22, "Caracoldetierra");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 22, "Caracoldetierraof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 22, "Caracoles de tierra: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 23, "pb_artesa_sal208");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 23, "pb_artesa_sal208");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 23, "Carnes pegajosas de regresado: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 24, "pb_artesa_efe06");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 24, "pb_artesa_efe06");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 24, "Carnes putrefactas del señor de las momias: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 25, "pb_artesa_rd");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 25, "pb_artesa_rd");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 25, "Carroñas de Xorn: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 26, "pb_artesa_lim03");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 26, "pb_artesa_lim03");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 26, "Cáscaras de batraco: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 27, "pb_artesa_dano08");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 27, "pb_artesa_dano08");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 27, "Caspa de ibrandlin: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 28, "pb_artesa_hab29");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 28, "pb_artesa_hab29");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 28, "Castigos de nálfeshni: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 29, "pb_artesa_car2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 29, "pb_artesa_car2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 29, "Caparazones de ankheg: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 30, "pb_artesa_ca");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 30, "pb_artesa_ca");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 30, "Cataclismos de tarasca: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 31, "pb_artesa_dano13");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 31, "pb_artesa_dano13");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 31, "Claridad de nyzh: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 32, "pb_artesa_dano01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 32, "pb_artesa_dano01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 32, "Colmillos de abishái: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 33, "basura_concha");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 33, "basura_concha");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 33, "Conchas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 34, "pb_artesa_sal212");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 34, "pb_artesa_sal212");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 34, "Consunciones de incorpóreo aterrador: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 35, "pb_artesa_hab23");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 35, "pb_artesa_hab23");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 35, "Corazones negro de pesadilla: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 36, "pb_artesa_sal102");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 36, "pb_artesa_sal102");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 36, "Cornaduras de unicornio negro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 37, "pb_artesa_lim05");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 37, "pb_artesa_lim05");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 37, "Cortezas de árbol oscuro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 38, "pb_artesa_efe18");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 38, "pb_artesa_efe18");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 38, "Crueldades de lamia: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 39, "gz_it_rope");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 39, "gz_it_rope");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 39, "Cuerdas con garfio: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 40, "pb_artesa_at");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 40, "pb_artesa_at");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 40, "Cuernos de behir: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 41, "sapo_cuero_rata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 41, "cuerorata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 41, "Cueros de rata: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 42, "sapo_cuero_serpi");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 42, "cueroserpi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 42, "Cueros de serpiente: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 43, "sapo_cuero_murci");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 43, "cueromurci");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 43, "Cueros de murciélago: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 44, "sapo_cuero_cani");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 44, "cuerocani");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 44, "Cueros de can infernal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 45, "sapo_cuero_cierv");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 45, "cuerocierv");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 45, "Cueros de ciervo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 46, "sapo_cuero_jabal");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 46, "cuerojabal");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 46, "Cueros de jabalí: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 47, "sapo_cuero_lagar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 47, "cuerolagar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 47, "Cueros de lagarto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 48, "sapo_cuero_lobo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 48, "cuerolobo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 48, "Cueros de lobo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 49, "sapo_cuero_loboi");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 49, "cueroloboi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 49, "Cueros de lobo invernal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 50, "sapo_cuero_oso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 50, "cuerooso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 50, "Cueros de oso: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 51, "sapo_cuero_rothe");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 51, "cuerorothe");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 51, "Cueros de rothé: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 52, "sapo_cuero_wyrm");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 52, "cuerowyrm");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 52, "Cueros de draco: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 53, "pb_artesa_hab09");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 53, "pb_artesa_hab09");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 53, "Conchas de tojánida: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 54, "pb_artesa_efe01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 54, "pb_artesa_efe01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 54, "Concentración de diablo astado: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 55, "pb_artesa_hab35");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 55, "pb_artesa_hab35");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 55, "Contratos de kolyarut: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 56, "NW_IT_MSMLMISC11");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 56, "NW_IT_MSMLMISC11");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 56, "Cristales de cuarzo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 57, "pb_artesa_poten1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 57, "pb_artesa_poten1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 57, "Cristales urdímbricos de Nishruu: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 58, "pb_artesa_poten2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 58, "pb_artesa_poten2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 58, "Cristales urdímbricos de Fénix: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 59, "pb_artesa_poten3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 59, "pb_artesa_poten3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 59, "Cristales urdímbricos de Quimera: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 60, "pb_artesa_poten4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 60, "pb_artesa_poten4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 60, "Cristales urdímbricos de Leviatán: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 61, "pb_artesa_hab36");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 61, "pb_artesa_hab36");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 61, "Crestas de dragón tortuga: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 62, "pb_artesa_sal200");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 62, "pb_artesa_sal200");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 62, "Dádivas de archiliche: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 63, "pb_artesa_sal214");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 63, "pb_artesa_sal214");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 63, "Deambulamientos de rávido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 64, "pb_artesa_car1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 64, "pb_artesa_car1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 64, "Dentinas de bestia oscurecida: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 65, "pb_artesa_vo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 65, "pb_artesa_vo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 65, "Derribos de sabueso yez: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 66, "pb_artesa_sal207");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 66, "pb_artesa_sal207");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 66, "Descomposiciones de broza movediza: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 67, "pb_artesa_clas02");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 67, "pb_artesa_clas02");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 67, "Devociones de mártir: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 68, "NW_IT_MSMLMISC06");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 68, "NW_IT_MSMLMISC06");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 68, "Dientes de bodak: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 69, "dientetiburon");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 69, "dientetiburon");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 69, "Dientes de tiburón: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 70, "pb_artesa_hab10");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 70, "pb_artesa_hab10");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 70, "Elasticidad de fasmo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 71, "pb_artesa_car5");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 71, "pb_artesa_car5");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 71, "Encantos de dríada: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 72, "pb_artesa_clas01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 72, "pb_artesa_clas01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 72, "Encantos de lilenda: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 73, "pb_artesa_clas10");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 73, "pb_artesa_clas10");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 73, "Enigmas de ginoesfinge: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 74, "pb_artesa_dano06");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 74, "pb_artesa_dano06");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 74, "Escamas de asabi: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 75, "esenciaInvisible");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 75, "esenciainvisible");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 75, "Esencias invisibles: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 76, "especiaSulfurosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 76, "especiasulfurosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 76, "Especias sulfurosas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 77, "pb_artesa_sal204");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 77, "pb_artesa_sal204");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 77, "Espectros de réprobo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 78, "espejodemano");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 78, "espejodemano");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 78, "Espejos de mano: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 79, "pb_artesa_dano10");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 79, "pb_artesa_dano10");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 79, "Espolones de dragónido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 80, "pb_artesa_efe20");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 80, "pb_artesa_efe20");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 80, "Estallidos de diablo de la sima: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 81, "estatuasirena");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 81, "estatuasirena");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 81, "Estatuas de sirena: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 82, "pb_artesa_hab33");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 82, "pb_artesa_hab33");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 82, "Estragos de quimera: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 83, "pb_artesa_sal203");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 83, "pb_artesa_sal203");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 83, "Eteriedad de serpiente de hielo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 84, "pb_artesa_hab18");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 84, "pb_artesa_hab18");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 84, "Excrecencias ósea de abolez mago: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 85, "pb_artesa_dano12");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 85, "pb_artesa_dano12");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 85, "Faz de hybsil: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 86, "pb_artesa_hab38");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 86, "pb_artesa_hab38");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 86, "Ferocidad de erinia: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 87, "pb_artesa_clas03");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 87, "pb_artesa_clas03");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 87, "Fervores de ent: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 88, "pb_artesa_hab01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 88, "pb_artesa_hab01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 88, "Firmeza de titán: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 89, "pb_artesa_hab11");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 89, "pb_artesa_hab11");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 89, "Flautines de sátiro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 90, "florLuminosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 90, "florluminosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 90, "Flores luminosas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 91, "pb_artesa_gemco0");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 91, "pb_artesa_gemco0");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 91, "Fragmentos de gólem de zafiro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 92, "pb_artesa_gemco1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 92, "pb_artesa_gemco1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 92, "Fragmentos de gólem de topacio: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 93, "pb_artesa_gemco2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 93, "pb_artesa_gemco2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 93, "Fragmentos de gólem de amatista: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 94, "pb_artesa_gemco3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 94, "pb_artesa_gemco3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 94, "Fragmentos de gólem de rubí: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 95, "pb_artesa_gemco4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 95, "pb_artesa_gemco4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 95, "Fragmentos de gólem de esmeralda: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 96, "pb_artesa_gemco5");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 96, "pb_artesa_gemco5");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 96, "Fragmentos de gólem de citrino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 97, "pb_artesa_gemco6");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 97, "pb_artesa_gemco6");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 97, "Fragmentos de gólem de diamante: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 98, "frutoFantasma");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 98, "frutofantasma");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 98, "Frutos fantasma: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 99, "pb_artesa_refor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 99, "pb_artesa_refor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 99, "Galope de centauro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 100, "pb_artesa_efe00");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 100, "pb_artesa_efe00");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 100, "Gas de dragón de oropel: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 101, "NW_IT_MSMLMISC07");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 101, "NW_IT_MSMLMISC07");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 101, "Glándulas de seda de trácnido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 102, "pb_artesa_dano07");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 102, "pb_artesa_dano07");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 102, "Gotas de ábalin: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 103, "pb_artesa_hab25");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 103, "pb_artesa_hab25");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 103, "Gracia de sirénido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 104, "Guadelaventurero");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 104, "Guadelaventurero");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 104, "Guías comerciales: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 105, "pb_artesa_dano09");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 105, "pb_artesa_dano09");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 105, "Hálitos de dragón del canto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 106, "humoGaseoso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 106, "humogaseoso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 106, "Humos gaseosos: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 107, "pb_artesa_car0");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 107, "pb_artesa_car0");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 107, "Ímpetu de gigante de la niebla: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 108, "pb_artesa_clas07");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 108, "pb_artesa_clas07");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 108, "Instintos de lobo terrible: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 109, "pb_artesa_hab20");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 109, "pb_artesa_hab20");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 109, "Instrucciones telepáticas de formícida reina: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 110, "pb_artesa_sal213");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 110, "pb_artesa_sal213");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 110, "Lenguas bífidas de Yuan-ti: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 111, "carplenyo_abeto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 111, "lenyoabeto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 111, "Leños de abeto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 112, "carplenyo_alamo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 112, "lenyoalamo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 112, "Leños de álamo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 113, "carplenyo_cedro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 113, "lenyocedro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 113, "Leños de cedro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 114, "carplenyo_cipres");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 114, "lenyocipres");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 114, "Leños de ciprés: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 115, "carplenyo_fresno");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 115, "lenyofresno");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 115, "Leños de fresno: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 116, "carplenyo_olmo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 116, "lenyoolmo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 116, "Leños de olmo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 117, "carplenyo_pino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 117, "lenyopino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 117, "Leños de pino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 118, "carplenyo_roble");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 118, "lenyoroble");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 118, "Leños de roble: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 119, "pb_artesa_peso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 119, "pb_artesa_peso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 119, "Levitaciones de lamparconte: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 120, "limoPutrefacto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 120, "limoputrefacto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 120, "Limos putrefactos: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 121, "lingoteHierro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 121, "lingotehierro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 121, "Lingotes de hierro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 122, "lingoteCobre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 122, "lingotecobre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 122, "Lingotes de cobre: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 123, "lingoteAcero");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 123, "lingoteacero");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 123, "Lingotes de acero: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 124, "lingotePlata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 124, "lingoteplata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 124, "Lingotes de plata: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 125, "lingoteHierrofrio");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 125, "lingotehierrofrio");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 125, "Lingotes de hierrofrío: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 126, "lingoteOro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 126, "lingoteoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 126, "Lingotes de oro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 127, "lingoteMithril");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 127, "lingotemithril");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 127, "Lingotes de mithril: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 128, "lingoteAdamantita");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 128, "lingoteadamantita");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 128, "Lingotes de adamantita: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 129, "pb_artesa_sal103");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 129, "pb_artesa_sal103");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 129, "Liviandad de béstia de Xvim: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 130, "pb_artesa_hab15");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 130, "pb_artesa_hab15");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 130, "Locura de derro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 131, "pb_artesa_hab07");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 131, "pb_artesa_hab07");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 131, "Luces carmesí de liche: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 132, "pb_artesa_hab31");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 132, "pb_artesa_hab31");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 132, "Luces cegadoras de bezekira: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 133, "pb_artesa_efe19");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 133, "pb_artesa_efe19");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 133, "Mandíbulas de aranea: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 134, "NW_IT_TRAP001");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 134, "NW_IT_TRAP001");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 134, "Materiales de trampero menor, estacas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 135, "pb_artesa_cm");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 135, "pb_artesa_cm");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 135, "Mordiscos de perro de guerra nessiano: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 136, "pb_artesa_hab13");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 136, "pb_artesa_hab13");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 136, "Mudez de birlador etéreo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 137, "pb_artesa_hab12");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 137, "pb_artesa_hab12");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 137, "Músculos de planotáreo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 138, "pb_artesa_clas06");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 138, "pb_artesa_clas06");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 138, "Nobleza de grifo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 139, "pb_artesa_efe03");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 139, "pb_artesa_efe03");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 139, "Óculos de bocón barbotante: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 140, "pb_artesa_dano05");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 140, "pb_artesa_dano05");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 140, "Ojos de contemplador: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 141, "NW_IT_MSMLMISC09");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 141, "NW_IT_MSMLMISC09");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 141, "Ojos de rakshasa: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 142, "pb_artesa_sal101");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 142, "pb_artesa_sal101");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 142, "Ojos oscuros carmesí de tritón de fuego: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 143, "pb_artesa_car4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 143, "pb_artesa_car4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 143, "Ojos rojos de medusa: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 144, "pb_artesa_efe16");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 144, "pb_artesa_efe16");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 144, "Órbitas oculares de grimórlock: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 145, "pb_artesa_efe14");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 145, "pb_artesa_efe14");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 145, "Órganos sensoriales de hongo fantasmal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 146, "pastaTerrosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 146, "pastaterrosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 146, "Pastas terrosas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 147, "pb_artesa_hab26");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 147, "pb_artesa_hab26");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 147, "Patas zancudas de aquerena: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 148, "pb_artesa_lim01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 148, "pb_artesa_lim01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 148, "Pelajes de araña subterránea: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 149, "pepitaHierro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 149, "pepitahierro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 149, "Pepitas de hierro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 150, "pepitaCobre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 150, "pepitacobre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 150, "Pepitas de cobre: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 151, "pepitaAcero");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 151, "pepitaacero");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 151, "Pepitas de acero: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 152, "pepitaPlata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 152, "pepitaplata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 152, "Pepitas de plata: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 153, "pepitaHierrofrio");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 153, "pepitahierrofrio");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 153, "Pepitas de hierrofrío: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 154, "pepitaOro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 154, "pepitaoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 154, "Pepitas de oro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 155, "pepitaMithril");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 155, "pepitamithril");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 155, "Pepitas de mithril: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 156, "pepitaAdamantita");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 156, "pepitaadamantita");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 156, "Pepitas de adamantita: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 157, "pb_artesa_dano02");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 157, "pb_artesa_dano02");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 157, "Pesuños de bestia de Málar: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 158, "picadaRocosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 158, "picadarocosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 158, "Picadas rocosas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 159, "pb_artesa_hab17");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 159, "pb_artesa_hab17");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 159, "Picos de águila gigante: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 160, "X1_IT_MSMLMISC01");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 160, "x1_it_msmlmisc01");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 160, "Piedras frías: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 161, "pb_artesa_reg");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 161, "pb_artesa_reg");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 161, "Pieles correosas de troll cazador: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 162, "pielderata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 162, "pielrata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 162, "Pieles de rata: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 163, "pellejoderata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 163, "pellejorata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 163, "Pellejos de rata: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 164, "pieldeserpiente");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 164, "pielserpi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 164, "Pieles de serpiente: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 165, "pieldeciervo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 165, "pielcierv");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 165, "Pieles de ciervo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 166, "pieldelobo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 166, "piellobo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 166, "Pieles de lobo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 167, "pieldejabali");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 167, "pieljabal");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 167, "Pieles de jabali: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 168, "pieldeloboinvern");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 168, "pielloboi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 168, "Pieles de lobo invernal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 169, "pieldeoso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 169, "pieloso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 169, "Pieles de oso: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 170, "pieldemurci");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 170, "pielmurci");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 170, "Pieles de murcielago: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 171, "pielderothe");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 171, "pielrothe");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 171, "Pieles de rothe: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 172, "pieldecani");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 172, "pielcani");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 172, "Pieles de can infernal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 173, "pieldelagar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 173, "piellagar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 173, "Pieles de lagarto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 174, "pieldewyrm");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 174, "pielwyrm");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 174, "Pieles de draco: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 175, "pb_artesa_hab30");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 175, "pb_artesa_hab30");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 175, "Pigmentaciones de mimeto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 176, "pb_artesa_hab24");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 176, "pb_artesa_hab24");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 176, "Pinzas de glabrezu: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 177, "pb_artesa_hab27");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 177, "pb_artesa_hab27");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 177, "Pezuñas de pegaso: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 178, "pb_artesa_efe25");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 178, "pb_artesa_efe25");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 178, "Plagas de murciélagos: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 179, "pb_artesa_lim04");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 179, "pb_artesa_lim04");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 179, "Plumas de aarakocra: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 180, "pb_artesa_clas09");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 180, "pb_artesa_clas09");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 180, "Plumas de couatl: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 181, "nw_it_creitem201");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 181, "nw_it_creitem201");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 181, "Plumas de gaviota: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 182, "pb_artesa_hab14");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 182, "pb_artesa_hab14");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 182, "Plumazón de roc: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 183, "pb_artesa_hab02");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 183, "pb_artesa_hab02");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 183, "Podredumbres de babau: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 184, "pb_artesa_polvo1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 184, "pb_artesa_polvo1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 184, "Polvos de abjuración: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 185, "pb_artesa_polvo3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 185, "pb_artesa_polvo3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 185, "Polvos de adivinación: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 186, "polvoantiluz");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 186, "polvoantiluzof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 186, "Polvos de antiluz: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 187, "pb_artesa_polvo2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 187, "pb_artesa_polvo2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 187, "Polvos de conjuración: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 188, "pb_artesa_polvo4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 188, "pb_artesa_polvo4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 188, "Polvos de encantamiento: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 189, "pb_artesa_polvo5");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 189, "pb_artesa_polvo5");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 189, "Polvos de evocación: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 190, "NW_IT_MSMLMISC19");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 190, "NW_IT_MSMLMISC19");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 190, "Polvos de hada: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 191, "pb_artesa_polvo6");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 191, "pb_artesa_polvo6");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 191, "Polvos de ilusión: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 192, "pb_artesa_polvo7");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 192, "pb_artesa_polvo7");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 192, "Polvos de nigromancia: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 193, "pb_artesa_polvo8");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 193, "pb_artesa_polvo8");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 193, "Polvos de transmutación: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 194, "pb_artesa_hab06");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 194, "pb_artesa_hab06");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 194, "Presas de búho gigante: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 195, "pb_artesa_efe02");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 195, "pb_artesa_efe02");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 195, "Presas de gusano púrpura: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 196, "pb_artesa_hab04");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 196, "pb_artesa_hab04");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 196, "Protecciones de solar: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 197, "pb_artesa_efe09");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 197, "pb_artesa_efe09");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 197, "Púas afiladas de gelugón: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 198, "pb_artesa_hab16");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 198, "pb_artesa_hab16");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 198, "Púas de salamandra: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 199, "pb_artesa_efe15");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 199, "pb_artesa_efe15");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 199, "Puños de trueno de marut: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 200, "raizPetrea");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 200, "raizpetrea");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 200, "Raíces pétreas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 201, "resinaSubterranea");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 201, "resinasubterrane");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 201, "Resinas subterráneas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 202, "pb_artesa_sal215");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 202, "pb_artesa_sal215");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 202, "Resistencias de slaad: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 203, "pb_artesa_rv");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 203, "pb_artesa_rv");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 203, "Sangres de vampiro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 204, "polvo_per");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 204, "polvoper");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 204, "Saquitos de arenilla de amatista: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 205, "polvo_aza");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 205, "polvoaza");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 205, "Saquitos de arenilla de azabache: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 206, "polvo_dia");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 206, "polvodia");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 206, "Saquitos de arenilla de diamante: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 207, "polvo_obs");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 207, "polvoobs");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 207, "Saquitos de arenilla de obsidiana: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 208, "polvo_rub");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 208, "polvorub");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 208, "Saquitos de arenilla de rubí: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 209, "polvo_zaf");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 209, "polvozaf");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 209, "Saquitos de arenilla de zafiro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 210, "polvo_top");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 210, "polvotop");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 210, "Saquitos de arenilla de topacio: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 211, "polvo_cua");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 211, "polvocua");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 211, "Saquitos de arenilla de cuarzo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 212, "setaNocturna");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 212, "setanocturna");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 212, "Setas nocturnas: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 213, "pb_artesa_hab37");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 213, "pb_artesa_hab37");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 213, "Siluetas serpentiforme de behir: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 214, "pb_artesa_hab05");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 214, "pb_artesa_hab05");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 214, "Siseos de ahogador: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 215, "carptablon_pino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 215, "tablonpino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 215, "Tablones de pino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 216, "carptablon_cipre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 216, "tabloncipres");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 216, "Tablones de ciprés: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 217, "carptablon_abeto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 217, "tablonabeto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 217, "Tablones de abeto: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 218, "carptablon_cedro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 218, "tabloncedro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 218, "Tablones de cedro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 219, "carptablon_alamo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 219, "tablonalamo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 219, "Tablones de álamo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 220, "carptablon_olmo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 220, "tablonolmo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 220, "Tablones de olmo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 221, "carptablon_roble");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 221, "tablonroble");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 221, "Tablones de roble: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 222, "carptablon_fresn");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 222, "tablonfresno");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 222, "Tablones de fresno: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 223, "pb_artesa_dano11");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 223, "pb_artesa_dano11");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 223, "Tentáculos de yokhol: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 224, "pb_artesa_sal211");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 224, "pb_artesa_sal211");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 224, "Tez de Fee'ri: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 225, "pb_artesa_hab08");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 225, "pb_artesa_hab08");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 225, "Tinieblas de noctámbulo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 226, "x2_it_dyeL23");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 226, "x2_it_dyel23");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 226, "Tintes de cuero negro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 227, "x2_it_dyeL48");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 227, "x2_it_dyel48");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 227, "Tintes de cuero verde: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 228, "pb_artesa_mej");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 228, "pb_artesa_mej");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 228, "Tutelaje de deva astral: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 229, "virutasResplandecientes");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 229, "virutasresplandecientes");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 229, "Virutas resplandecientes: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 230, "pb_artesa_dano00");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 230, "pb_artesa_dano00");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 230, "Vellosidades de alaghi: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 231, "pb_artesa_efe07");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 231, "pb_artesa_efe07");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 231, "Verrugas de saga nocturna: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 232, "pb_artesa_sal206");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 232, "pb_artesa_sal206");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 232, "Vuelos de semicelestial: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 233, "HC_Tinderbox");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 233, "HC_Tinderbox");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 233, "Yesca y pedernal: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 234, "pb_artesa_efe05");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 234, "pb_artesa_efe05");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 234, "Zarpas de can trasguero: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 235, "zumoAcuoso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 235, "zumoacuoso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 235, "Zumos acuosos: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 236, "pepitaDlarun");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 236, "pepitaDlarun");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 236, "Pepita de dlarun: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 237, "pepitaHizagkuur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 237, "pepitaHizagkuur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 237, "Pepita de hizagkuur: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 238, "pepitaAceroscuro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 238, "pepitaAceroscuro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 238, "Pepita de hierro meteórico: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 239, "pepitaPlatino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 239, "pepitaPlatino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 239, "Pepita de platino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 240, "pepitaArandur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 240, "pepitaArandur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 240, "Pepita de arandur: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 241, "pepitaMetalvivo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 241, "pepitaMetalvivo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 241, "Pepita de metal vivo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 242, "pepitaCarbon");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 242, "pepitaCarbon");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 242, "Pepita de carbón: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 243, "pepitaDerretido");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 243, "pepitaDerretido");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 243, "Pepita de metal derretido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 244, "lingoteDlarun");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 244, "lingoteDlarun");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 244, "Lingote de dlarun: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 245, "lingoteHizagkuur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 245, "lingoteHizagkuur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 245, "Lingote de hizagkuur: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 246, "lingoteAceroscuro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 246, "lingoteAceroscuro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 246, "Lingote de aceroscuro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 247, "lingotePlatino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 247, "lingotePlatino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 247, "Lingote de platino: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 248, "lingoteArandur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 248, "lingoteArandur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 248, "Lingote de arandur: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 249, "lingoteMetalvivo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 249, "lingoteMetalvivo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 249, "Lingote de metal vivo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 250, "lingoteDerretido");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 250, "lingoteDerretido");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 250, "Lingote de hierro enardecido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 251, "pielroedor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 251, "pielroedor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 251, "Piel de Roedor: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 252, "pielherbivoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 252, "pielherbivoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 252, "Piel de Hervivoro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 253, "pielbestia");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 253, "pielbestia");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 253, "Piel de Bestia: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 254, "pielbestiag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 254, "pielbestiag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 254, "Piel de Bestia Grande: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 255, "pielmitica");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 255, "pielmitica");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 255, "Piel de bestia mitica: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 256, "pielmiticag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 256, "pielmiticag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 256, "Piel de bestia mitica Grande: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 257, "pieldracof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 257, "pieldracof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 257, "Piel de Dragon de Fuego: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 258, "pieldracoh");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 258, "pieldracoh");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 258, "Piel de Dragon de Hielo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 259, "pieldracoa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 259, "pieldracoa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 259, "Piel de Dragon de Acido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 260, "pieldracor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 260, "pieldracor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 260, "Piel de Dragon de Rayo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 261, "cuero_roedor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 261, "cuero_roedor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 261, "Cuero de Roedor: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 262, "cuero_herbivoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 262, "cuero_herbivoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 262, "Cuero de Herbivoro: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 263, "cuero_bestia");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 263, "cuero_bestia");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 263, "Cuero de Bestia: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 264, "cuero_bestiag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 264, "cuero_bestiag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 264, "Cuero de Bestia Grande: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 265, "cuero_mitica");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 265, "cuero_mitica");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 265, "Cuero de Bestia Mitica: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 266, "cuero_miticag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 266, "cuero_miticag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 266, "Cuero de Bestia Mitica Grande: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 267, "cuero_dragof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 267, "cuero_dragof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 267, "Cuero de Dragon de Fuego: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 268, "cuero_dragoh");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 268, "cuero_dragoh");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 268, "Cuero de Dragon de Hielo: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 269, "cuero_dragoa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 269, "cuero_dragoa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 269, "Cuero de Dragon de Acido: " );
  SetLocalArrayString(oUbicado, "sTagIngOficio", 270, "cuero_dragor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 270, "cuero_dragor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 270, "Cuero de Dragon de Rayo: " );

  /*
      Faltarian estos, pero como la mayoria son apilables y no van bien con
      este sistema mejor los dejamos en paz

      NW_IT_PICKS001
      diopsidoestrella
      shandon
      ust_plaksfher
      medicinebag
      NW_IT_MEDKIT001
      X1_WMGRENADE006
  */

  return;
}
