-- CNR catalogue seed: professions, stations, station tools and materials.
-- Generated by migration/build_catalogue.py; do not edit by hand.
--
-- Apply 03_catalogue.sql straight after this file. Reseeding materials
-- and stations invalidates every recipe that points at them, so the
-- catalogue is cleared here in dependency order and rebuilt there.
-- Without this, DELETE FROM cnr_material fails on fk_recipe_material.

START TRANSACTION;

DELETE FROM cnr_recipe_property;
DELETE FROM cnr_recipe_component;
DELETE FROM cnr_recipe;
DELETE FROM cnr_category;
DELETE FROM cnr_station_tool;
DELETE FROM cnr_material;
DELETE FROM cnr_station;
DELETE FROM cnr_profession;

INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (1,'Herreria','Herrería',0,0,2,1000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (2,'Carpinteria','Carpintería',1,1,0,2000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (3,'Peleteria','Peletería',2,1,2,3000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (4,'Alquimia','Alquimia',3,4,3,4000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (5,'Joyeria','Joyería',4,5,4,5000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (6,'Arcano','Arcano',5,3,4,6000);
INSERT INTO cnr_profession (profession_id,code,display_name,skill_index,ability_1,ability_2,id_block) VALUES (7,'Sastreria','Sastrería',6,1,5,7000);

INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrAlchemyTable',4,'Mesa de alquimia','product','cnr_alchemy_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrAnvilSmith',1,'Yunque de herrero','product','cnr_anvil_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrCuringTub',3,'Tina de curtido','material','cnr_curing_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrForgePublic',1,'Forja','material','cnr_forge_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrHebCauldron',4,'Caldero de hierbas','material','cnr_alchemy_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrJewelersBench',5,'Mesa de joyero','product','cnr_jeweler_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrTailorsTable',3,'Mesa de peletero','product','cnr_tailor_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrSewingTable',7,'Mesa de sastrería','product','cnr_tailor_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrSawTable',2,'Tabla de serrería','material','cnr_carp_anim');
INSERT INTO cnr_station (tag,profession_id,display_name,produces,anim_script) VALUES ('cnrCarpsBench',2,'Banco de carpintero','product','cnr_carp_anim');

INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_martligero','Martillo ligero de herrero','equipped',4.0,1 FROM cnr_station WHERE tag='cnrAnvilSmith';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_gu_fundid','Guantes de Fundidor','equipped',4.0,1 FROM cnr_station WHERE tag='cnrForgePublic';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_aguja','Aguja grande','equipped',3.0,1 FROM cnr_station WHERE tag='cnrTailorsTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_kit_cuero','Kit de herramientas para trabajar el cuero','inventory',4.0,2 FROM cnr_station WHERE tag='cnrTailorsTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_gu_alquim','Guantes de Alquimista','equipped',4.0,1 FROM cnr_station WHERE tag='cnrAlchemyTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_gu_cocina','Guantes de Cocinero','equipped',4.0,1 FROM cnr_station WHERE tag='cnrHebCauldron';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_aguja','Aguja grande','equipped',3.0,1 FROM cnr_station WHERE tag='cnrSewingTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_kit_sastre','Kit de herramientas del Sastre','inventory',4.0,2 FROM cnr_station WHERE tag='cnrSewingTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_kit_serr','Kit de herramientas del serrador','inventory',4.0,1 FROM cnr_station WHERE tag='cnrSawTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_sierra','Sierra del serrador','inventory',4.0,2 FROM cnr_station WHERE tag='cnrSawTable';
INSERT INTO cnr_station_tool (station_id,tool_tag,display_name,access_mode,breakage_chance,sort_order) SELECT station_id,'cnr_t_kit_carp','Kit de herramientas del carpintero','inventory',4.0,1 FROM cnr_station WHERE tag='cnrCarpsBench';

INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Cobre','Cobre',1,1,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Hierro','Hierro',1,2,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Acero','Acero',1,3,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Plata','Plata',2,4,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Hierrofrio','Hierrofrio',2,5,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Oro','Oro',2,6,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Platino','Platino',2,7,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Hierro Enardecido','Hierro Enardecido',2,8,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Aceroscuro','Aceroscuro',3,9,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Dlarun','Dlarun',3,10,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Hizagkuur','Hizagkuur',3,11,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Arandur','Arandur',3,12,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Metal Vivo','Metal Vivo',4,13,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Mithril','Mithril',4,14,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (1,'Adamantita','Adamantita',4,15,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de roedor','Cuero de roedor',1,1,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de roedor','Cuero de roedor',1,1,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de herbívoro','Cuero de herbívoro',1,2,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de herbívoro','Cuero de herbívoro',1,2,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de bestia salvaje','Cuero de bestia salvaje',2,3,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de bestia salvaje','Cuero de bestia salvaje',2,3,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de bestia salvaje grande','Cuero de bestia salvaje grande',2,4,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de bestia salvaje grande','Cuero de bestia salvaje grande',2,4,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de bestia mítica','Cuero de bestia mítica',3,5,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de bestia mítica','Cuero de bestia mítica',3,5,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de bestia mítica gruesa','Cuero de bestia mítica gruesa',3,6,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de bestia mítica gruesa','Cuero de bestia mítica gruesa',3,6,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de dragón de fuego','Cuero de dragón de fuego',4,7,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de dragón de fuego','Cuero de dragón de fuego',4,7,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de dragón de hielo','Cuero de dragón de hielo',4,8,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de dragón de hielo','Cuero de dragón de hielo',4,8,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de dragón de ácido','Cuero de dragón de ácido',4,9,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de dragón de ácido','Cuero de dragón de ácido',4,9,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (3,'Cuero de dragón de rayo','Cuero de dragón de rayo',4,10,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (7,'Cuero de dragón de rayo','Cuero de dragón de rayo',4,10,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Pino','Pino',1,1,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Cedro','Cedro',1,2,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Abeto','Abeto',2,3,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Roble','Roble',2,4,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Sombralto','Sombralto',3,5,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Leñocaso','Leñocaso',3,6,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Zalantar','Zalantar',4,7,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (2,'Maderadique','Maderadique',4,8,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_cor','Corvidar',1,1,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_cuar','Cuarzo hilaino',1,2,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_jade','Jade de tumba',1,3,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_lagroj','Lágrima Roja',1,4,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_obs','Obsidiana',1,5,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_pic','Piedra pícara',1,6,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_top','Topacio',1,7,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_opalo','Ópalo',1,8,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_opaloa','Ópalo de agua',1,9,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_opalof','Ópalo de fuego',1,10,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_amat','Amatista',2,11,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_aza','Azabache',2,12,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_bel','Beljuril',2,13,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_diam','Diamante',2,14,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_opalon','Opalo negro',2,15,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_orblen','Orblen',2,16,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_orlo','Orlo',2,17,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_zaf','Zafiro',2,18,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_zen','Zendalur',2,19,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_amar','Amarazha',3,20,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_barra','Barra lunar',3,21,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_esme','Esmeralda',3,22,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_jac','Jacinto',3,23,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_lagrey','Lágrima del rey',3,24,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_rubi','Rubí',3,25,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_rubie','Rubí estrella',3,26,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_zafe','Zafiro Estrella',3,27,1);
INSERT INTO cnr_material (profession_id,code,display_name,tier,sort_order,enabled) VALUES (5,'cnr_g_zafn','Zafiro negro',3,28,1);

COMMIT;
