"""Arcane enchanting: browsing and transactional editing.

Arcane is the one trade with no recipes. `cnr_recipe` holds nothing for
profession 6 and never did, which is why the panel's recipe tab reported
"0 recetas encontradas" for it: the number was right and the question was
wrong. What arcane has is `cnr_arcane_property`, one row per enchantment a
player may buy, with `cnr_arcane_step` for the amounts it is sold in and
`cnr_arcane_group` for the items it may be put on.

This router gives that model the same capabilities the recipe catalogue has:
listing with search, filters and paging, a detail view, a transactional edit
guarded by the same profession scope, optimistic concurrency, and an audit
trail. The differences from `recipes.py` are the two the data forces, and both
are deliberate:

* **The concurrency token is a digest, not a timestamp.** These tables are
  generated by `migration/build_arcane.py` and carry no `updated_at`. Rather
  than add a column to a table `db-apply.sh` drops and rebuilds, the client
  sends back the fingerprint it was given and the server recomputes it.
* **`PROPERTY_DEFINITIONS` is not applied.** Sixteen of the twenty-five arcane
  property types are absent from it, and eighteen shipped steps of types it
  does know would be rejected by its ranges, so enforcing it would refuse data
  the game already runs. Validation here is structural. The design vocabulary
  belongs to `documentation/oficios/arcano.json` and is enforced when
  `build_arcane.py` regenerates the SQL.
"""

from datetime import UTC, datetime

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import String, cast, func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, selectinload

from app.arcane_fingerprint import arcane_fingerprint, arcane_group_fingerprint
from app.base_item_labels import BASE_ITEM_LABELS
from app.database import get_db
from app.dependencies import (
    SessionContext,
    require_csrf,
    require_profession_edit,
    require_recipe_viewer,
    require_writes_enabled,
)
from app.models import (
    ArcaneGroup,
    ArcaneGroupBase,
    ArcaneProperty,
    ArcaneRevision,
    ArcaneStep,
    EditorUser,
)
from app.schemas import (
    ArcaneBaseItemLabel,
    ArcaneBaseItemOut,
    ArcaneDetail,
    ArcaneGroupDetail,
    ArcaneGroupOut,
    ArcaneGroupUpdate,
    ArcaneListItem,
    ArcaneListPage,
    ArcaneReferenceData,
    ArcaneStepOut,
    ArcaneUpdate,
)

router = APIRouter(tags=["arcane"])

# Arcane is profession 6 in cnr_profession. Editing it is scoped exactly as any
# other trade is: view_recipes, edit_recipes and profession 6 in the user's
# editable set. No new permission is introduced, so an existing administrator
# grants arcane access the same way they grant carpentry.
ARCANE_PROFESSION_ID = 6


def _group_out(group: ArcaneGroup) -> ArcaneGroupOut:
    return ArcaneGroupOut(
        group_id=group.group_id,
        code=group.code,
        display_name=group.display_name,
        any_base=bool(group.any_base),
        bases=[ArcaneBaseItemOut.model_validate(item) for item in group.bases],
    )


def _detail(prop: ArcaneProperty) -> ArcaneDetail:
    return ArcaneDetail(
        arcane_id=prop.arcane_id,
        section=prop.section,
        display_name=prop.display_name,
        group_id=prop.group_id,
        tier=prop.tier,
        essence_resref=prop.essence_resref,
        essence_name=prop.essence_name,
        crystal_resref=prop.crystal_resref,
        crystal_name=prop.crystal_name,
        ubicacion=prop.ubicacion,
        property_type=prop.property_type,
        subtype=prop.subtype,
        min_level=prop.min_level,
        dc=prop.dc,
        supported=bool(prop.supported),
        note=prop.note,
        group=_group_out(prop.group),
        steps=[ArcaneStepOut.model_validate(step) for step in prop.steps],
        fingerprint=arcane_fingerprint(prop),
    )


def _snapshot(prop: ArcaneProperty) -> dict:
    return _detail(prop).model_dump(mode="json")


@router.get("/arcane/references", response_model=ArcaneReferenceData)
def arcane_references(
    _: EditorUser = Depends(require_recipe_viewer),
    db: Session = Depends(get_db),
) -> ArcaneReferenceData:
    groups = list(
        db.scalars(
            select(ArcaneGroup)
            .options(selectinload(ArcaneGroup.bases))
            .order_by(ArcaneGroup.display_name)
        )
    )
    sections = list(
        db.scalars(select(ArcaneProperty.section).distinct().order_by(ArcaneProperty.section))
    )
    property_types = list(
        db.scalars(
            select(ArcaneProperty.property_type).distinct().order_by(ArcaneProperty.property_type)
        )
    )
    return ArcaneReferenceData(
        groups=[_group_out(group) for group in groups],
        sections=sections,
        property_types=property_types,
        # Every base item the 2DA defines, not only the ones already in a
        # group: the point of the group editor is to add the ones that are not.
        base_item_labels=[
            ArcaneBaseItemLabel(base_item=base_item, label=label)
            for base_item, label in sorted(BASE_ITEM_LABELS.items())
        ],
    )


@router.get("/arcane/properties", response_model=ArcaneListPage)
def list_arcane_properties(
    _: EditorUser = Depends(require_recipe_viewer),
    db: Session = Depends(get_db),
    search: str | None = Query(default=None, max_length=96),
    section: str | None = Query(default=None, max_length=32),
    group_id: int | None = None,
    tier: int | None = Query(default=None, ge=1, le=4),
    property_type: str | None = Query(default=None, max_length=32),
    supported: bool | None = None,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=100, ge=1, le=250),
) -> ArcaneListPage:
    step_count = (
        select(ArcaneStep.arcane_id, func.count().label("count"))
        .group_by(ArcaneStep.arcane_id)
        .subquery()
    )
    base_count = (
        select(ArcaneGroupBase.group_id, func.count().label("count"))
        .group_by(ArcaneGroupBase.group_id)
        .subquery()
    )
    query = (
        select(
            ArcaneProperty,
            ArcaneGroup.display_name,
            ArcaneGroup.any_base,
            func.coalesce(step_count.c.count, 0),
            func.coalesce(base_count.c.count, 0),
        )
        .join(ArcaneGroup, ArcaneProperty.group_id == ArcaneGroup.group_id)
        .outerjoin(step_count, step_count.c.arcane_id == ArcaneProperty.arcane_id)
        .outerjoin(base_count, base_count.c.group_id == ArcaneGroup.group_id)
        .options(selectinload(ArcaneProperty.steps))
    )
    conditions = []
    if search:
        pattern = f"%{search}%"
        conditions.append(
            or_(
                ArcaneProperty.display_name.like(pattern),
                ArcaneProperty.essence_name.like(pattern),
                cast(ArcaneProperty.arcane_id, String).like(pattern),
            )
        )
    if section is not None:
        conditions.append(ArcaneProperty.section == section)
    if group_id is not None:
        conditions.append(ArcaneProperty.group_id == group_id)
    if tier is not None:
        conditions.append(ArcaneProperty.tier == tier)
    if property_type is not None:
        conditions.append(ArcaneProperty.property_type == property_type)
    if supported is not None:
        conditions.append(ArcaneProperty.supported.is_(supported))
    if conditions:
        query = query.where(*conditions)

    total = db.scalar(select(func.count()).select_from(query.order_by(None).subquery())) or 0
    rows = db.execute(query.order_by(ArcaneProperty.arcane_id).offset(offset).limit(limit)).all()
    items = [
        ArcaneListItem(
            arcane_id=row[0].arcane_id,
            display_name=row[0].display_name,
            section=row[0].section,
            group_id=row[0].group_id,
            group_name=row[1],
            any_base=bool(row[2]),
            tier=row[0].tier,
            min_level=row[0].min_level,
            dc=row[0].dc,
            property_type=row[0].property_type,
            subtype=row[0].subtype,
            essence_name=row[0].essence_name,
            crystal_name=row[0].crystal_name,
            supported=bool(row[0].supported),
            step_count=row[3],
            # any_base means every base item qualifies and the join table is not
            # read, so a count of zero there is complete coverage, not none.
            base_item_count=row[4],
            fingerprint=arcane_fingerprint(row[0]),
        )
        for row in rows
    ]
    return ArcaneListPage(items=items, total=total, offset=offset, limit=limit)


def _load(db: Session, arcane_id: int, lock: bool = False) -> ArcaneProperty:
    query = (
        select(ArcaneProperty)
        .where(ArcaneProperty.arcane_id == arcane_id)
        .options(
            selectinload(ArcaneProperty.steps),
            selectinload(ArcaneProperty.group).selectinload(ArcaneGroup.bases),
        )
    )
    if lock:
        query = query.with_for_update(of=ArcaneProperty)
    prop = db.scalar(query)
    if prop is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Propiedad arcana no encontrada"
        )
    return prop


@router.get("/arcane/properties/{arcane_id}", response_model=ArcaneDetail)
def get_arcane_property(
    arcane_id: int,
    _: EditorUser = Depends(require_recipe_viewer),
    db: Session = Depends(get_db),
) -> ArcaneDetail:
    return _detail(_load(db, arcane_id))


@router.put(
    "/arcane/properties/{arcane_id}",
    response_model=ArcaneDetail,
    dependencies=[Depends(require_writes_enabled)],
)
def update_arcane_property(
    arcane_id: int,
    payload: ArcaneUpdate,
    context: SessionContext = Depends(require_csrf),
    db: Session = Depends(get_db),
) -> ArcaneDetail:
    require_profession_edit(context.user, ARCANE_PROFESSION_ID)

    prop = _load(db, arcane_id, lock=True)

    if arcane_fingerprint(prop) != payload.fingerprint:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="La propiedad cambió después de abrirla; recarga antes de guardar",
        )

    if db.get(ArcaneGroup, payload.group_id) is None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="El grupo de objetos indicado no existe",
        )

    before = _snapshot(prop)
    for field in (
        "section",
        "display_name",
        "group_id",
        "tier",
        "essence_resref",
        "essence_name",
        "crystal_resref",
        "crystal_name",
        "ubicacion",
        "property_type",
        "subtype",
        "min_level",
        "dc",
        "supported",
        "note",
    ):
        setattr(prop, field, getattr(payload, field))

    try:
        prop.steps.clear()
        db.flush()
        prop.steps.extend(ArcaneStep(**step.model_dump()) for step in payload.steps)
        db.flush()
        db.refresh(prop)
        after = _snapshot(prop)
        db.add(
            ArcaneRevision(
                target_kind="property",
                arcane_id=prop.arcane_id,
                actor_user_id=context.user.user_id,
                action="update",
                before_json=before,
                after_json=after,
                changed_at=datetime.now(UTC).replace(tzinfo=None),
            )
        )
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="La propiedad incumple una restricción del catálogo arcano",
        ) from exc
    return _detail(_load(db, arcane_id))


def _group_detail(group: ArcaneGroup, property_count: int) -> ArcaneGroupDetail:
    return ArcaneGroupDetail(
        group_id=group.group_id,
        code=group.code,
        display_name=group.display_name,
        any_base=bool(group.any_base),
        bases=[ArcaneBaseItemOut.model_validate(item) for item in group.bases],
        property_count=property_count,
        fingerprint=arcane_group_fingerprint(group),
    )


def _load_group(db: Session, group_id: int, lock: bool = False) -> ArcaneGroup:
    query = (
        select(ArcaneGroup)
        .where(ArcaneGroup.group_id == group_id)
        .options(selectinload(ArcaneGroup.bases))
    )
    if lock:
        query = query.with_for_update(of=ArcaneGroup)
    group = db.scalar(query)
    if group is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Grupo arcano no encontrado"
        )
    return group


def _property_count(db: Session, group_id: int) -> int:
    return (
        db.scalar(
            select(func.count())
            .select_from(ArcaneProperty)
            .where(ArcaneProperty.group_id == group_id)
        )
        or 0
    )


@router.get("/arcane/groups", response_model=list[ArcaneGroupDetail])
def list_arcane_groups(
    _: EditorUser = Depends(require_recipe_viewer),
    db: Session = Depends(get_db),
) -> list[ArcaneGroupDetail]:
    groups = list(
        db.scalars(
            select(ArcaneGroup)
            .options(selectinload(ArcaneGroup.bases))
            .order_by(ArcaneGroup.display_name)
        )
    )
    counts = dict(
        db.execute(
            select(ArcaneProperty.group_id, func.count()).group_by(ArcaneProperty.group_id)
        ).all()
    )
    return [_group_detail(group, counts.get(group.group_id, 0)) for group in groups]


@router.get("/arcane/groups/{group_id}", response_model=ArcaneGroupDetail)
def get_arcane_group(
    group_id: int,
    _: EditorUser = Depends(require_recipe_viewer),
    db: Session = Depends(get_db),
) -> ArcaneGroupDetail:
    return _group_detail(_load_group(db, group_id), _property_count(db, group_id))


@router.put(
    "/arcane/groups/{group_id}",
    response_model=ArcaneGroupDetail,
    dependencies=[Depends(require_writes_enabled)],
)
def update_arcane_group(
    group_id: int,
    payload: ArcaneGroupUpdate,
    context: SessionContext = Depends(require_csrf),
    db: Session = Depends(get_db),
) -> ArcaneGroupDetail:
    """Edit which base items a group admits, and what each costs in crystals.

    A group is shared by every property that points at it, so this is the one
    arcane edit that changes several recipes' worth of behaviour at once. The
    response says how many properties that is, and the audit row keeps the
    whole before and after.

    The group's `code` is not editable. It is the identifier the design and the
    generator use to refer to the group; renaming it here would leave the two
    disagreeing with nothing to notice it.
    """
    require_profession_edit(context.user, ARCANE_PROFESSION_ID)

    group = _load_group(db, group_id, lock=True)

    if arcane_group_fingerprint(group) != payload.fingerprint:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="El grupo cambió después de abrirlo; recarga antes de guardar",
        )

    unknown = sorted(
        base.base_item for base in payload.bases if base.base_item not in BASE_ITEM_LABELS
    )
    if unknown:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=(
                "Estos tipos base no existen en baseitems.2da: "
                + ", ".join(str(item) for item in unknown)
            ),
        )

    count = _property_count(db, group_id)
    before = _group_detail(group, count).model_dump(mode="json")

    group.display_name = payload.display_name
    group.any_base = payload.any_base

    try:
        group.bases.clear()
        db.flush()
        group.bases.extend(
            ArcaneGroupBase(base_item=base.base_item, crystal_cost=base.crystal_cost)
            for base in payload.bases
        )
        db.flush()
        db.refresh(group)
        after = _group_detail(group, count).model_dump(mode="json")
        db.add(
            ArcaneRevision(
                target_kind="group",
                arcane_id=group.group_id,
                actor_user_id=context.user.user_id,
                action="update",
                before_json=before,
                after_json=after,
                changed_at=datetime.now(UTC).replace(tzinfo=None),
            )
        )
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="El grupo incumple una restricción del catálogo arcano",
        ) from exc
    return _group_detail(_load_group(db, group_id), count)
