"""The concurrency token for an arcane property.

The recipe editor guards a concurrent edit with `cnr_recipe.updated_at`. The
arcane tables have no such column: they are generated by
`migration/build_arcane.py` and dropped and rebuilt by `db-apply.sh`, so a
timestamp added to them would be a column the game schema carries for the
panel's sake and would reset on every catalogue apply anyway.

A digest of the row and its steps gives the same guarantee without that. The
client is handed the token with the detail it opened and sends it back with
the save; the server recomputes it and refuses the write if it no longer
matches, which is exactly the condition "somebody else changed this while you
had it open".

This module deliberately imports nothing from the framework so the rule can be
tested on its own.
"""

import hashlib
import json
from typing import Any


def _step_payload(step: Any) -> dict[str, Any]:
    return {
        "essences": step.essences,
        "subtype": step.subtype,
        "value1": step.value1,
        "value2": step.value2,
        "xp": step.xp,
        "display_value": step.display_value,
    }


def arcane_fingerprint(prop: Any) -> str:
    """Digest one arcane property and its steps.

    Everything an edit may change goes in, so two editors who opened the same
    property and changed different fields cannot both save. Nothing outside the
    edit surface goes in, so a catalogue rebuild that writes the same values
    back produces the same token and does not invalidate an open form.

    Steps are ordered by their essence count rather than by whatever order the
    database returned, so the token does not depend on row order.
    """
    payload = {
        "arcane_id": prop.arcane_id,
        "section": prop.section,
        "display_name": prop.display_name,
        "group_id": prop.group_id,
        "tier": prop.tier,
        "essence_resref": prop.essence_resref,
        "essence_name": prop.essence_name,
        "crystal_resref": prop.crystal_resref,
        "crystal_name": prop.crystal_name,
        "ubicacion": prop.ubicacion,
        "property_type": prop.property_type,
        "subtype": prop.subtype,
        "min_level": prop.min_level,
        "dc": prop.dc,
        "supported": bool(prop.supported),
        "note": prop.note,
        "steps": [
            _step_payload(step) for step in sorted(prop.steps, key=lambda item: item.essences)
        ],
    }
    encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()
