/// ----------------------------------------------------------------------------
/// @system  CNR Arcane
/// @file    cnr_i_arcane
/// @author  Dhraax
/// @brief   The arcane trade's logic. Reads the table, queries the catalogue
///          and works out what can be enchanted and with what. It draws
///          nothing: the NUI window and the applier both call in here, and
///          this file knows about neither of them.
///
///          Arcane does not craft. It takes an item that already exists and
///          adds a property to it, so there are no recipes: the window builds
///          the request and the applier revalidates it against these same
///          functions.
///
///          Tables, generated by migration/build_arcane.py:
///            cnr_arcane_group        the eight equipment groups
///            cnr_arcane_group_base   which base item belongs to each group
///            cnr_arcane_property     the 105 properties
///            cnr_arcane_step         how many essences buy which value
/// modified by: Dhraax
/// ----------------------------------------------------------------------------

#include "nwnx_sql"
#include "cnr_i_skill"

// -----------------------------------------------------------------------------
//                                  Constants
// -----------------------------------------------------------------------------

/// Arcane is profession 6 and its skill_index is 5; CnrSkill counts from 1.
const int CNR_ARC_PROFESSION = 6;
const int CNR_ARC_SKILL      = 6;

/// The mark every trade stamps on what it makes. Without it an item is not
/// enchantable, which is what stops bought or quest goods getting through.
const string CNR_ARC_VAR_TRADE = "CNR_OFICIO";

/// The mark the enchantment itself leaves. An item is enchanted once.
const string CNR_ARC_VAR_DONE = "CNR_ENCANTADO";

/// Separators for the serialized rows the queries return. The crafting engine
/// uses the same convention in cnr_i_craft.
const string CNR_ARC_SEP_FIELD = "|";
const string CNR_ARC_SEP_ROW   = ";";

/// The hardest roll the trade asks for. It is not a number of its own: the
/// rest of the CNR already spreads every recipe's DC over 10 to 35, so the
/// arcane ladders stop where the other trades do.
///
/// A property whose last rung would run past it starts lower instead, which
/// keeps every rung exactly one apart. Eleven of the hundred and five are
/// pulled down that way; see documentation/oficios/cnr/arcane-fix-plan.md.
const int CNR_ARC_DC_CEILING = 35;

/// State of the item sitting in the table.
const int CNR_ARC_TARGET_OK    = 0;  ///< exactly one, and valid
const int CNR_ARC_TARGET_NONE  = 1;  ///< nothing enchantable inside
const int CNR_ARC_TARGET_MANY  = 2;  ///< more than one: none is chosen
const int CNR_ARC_TARGET_DONE  = 3;  ///< the only one there is enchanted

// -----------------------------------------------------------------------------
//                              Function Prototypes
// -----------------------------------------------------------------------------

/// @brief Cuts field n out of a serialized row.
/// @param sRow The row, fields separated by CNR_ARC_SEP_FIELD.
/// @param iIndex Zero-based field index.
/// @returns The field, or an empty string when the row is shorter than that.
string CnrArc_Field(string sRow, int iIndex);

/// @brief Can this item take an enchantment?
/// @param oItem Item to examine.
/// @returns TRUE when a trade made it and it is not enchanted already.
int CnrArc_IsEnchantable(object oItem);

/// @brief State of the table with respect to the item to enchant.
/// @param oTable The station placeable.
/// @returns One of the CNR_ARC_TARGET_* constants.
int CnrArc_TargetState(object oTable);

/// @brief The item that is going to be enchanted.
/// @param oTable The station placeable.
/// @returns The only candidate, or OBJECT_INVALID unless there is exactly one.
object CnrArc_GetTarget(object oTable);

/// @brief How many units of a material are in the table.
/// @param oTable The station placeable.
/// @param sTag Material tag; in arcane the tag and the resref are the same.
/// @returns The total, counting stacks.
int CnrArc_CountMaterial(object oTable, string sTag);

/// @brief The player's arcane level.
/// @param oPC The crafter.
/// @returns Their level in the arcane tradeskill.
int CnrArc_GetLevel(object oPC);

/// @brief SQL for how many steps a property has.
/// @returns A scalar subquery, valid wherever cnr_arcane_property is aliased
///     "p". The entry DC is pinned to it, so a long ladder starts lower.
string CnrArc_SqlStepCount();

/// @brief SQL for a step's place in its property's ladder, counting from 1.
/// @returns A scalar subquery, valid wherever cnr_arcane_step is aliased "s".
///
/// The rung is what the DC climbs with, never the essence count. Half the
/// properties do not spend one essence per rung - the damage ones go 1, 2, 4,
/// 6, 8, and the truncated spell-slot progressions go 2, 3, 4 - so pricing by
/// essences spent would skip a DC on those spell slots and several on damage.
string CnrArc_SqlStepRank();

/// @brief SQL for a property's entry DC, the DC of its first step.
/// @returns An expression, valid wherever cnr_arcane_property is aliased "p".
///     Adding the step's rung, less one, gives the DC of any step.
///
/// The DC lives on the step and not on the property, and it is computed here,
/// in SQL, rather than in NWScript on purpose: the window shows the odds and
/// the applier rolls against them from two different files, and they used to
/// agree only because both read the same column. Deriving both from this one
/// expression is what stops them drifting apart.
string CnrArc_SqlEntryDC();

/// @brief Properties this item admits.
/// @param oPC The crafter, for their trade level.
/// @param iBaseItem GetBaseItemType() of the item to enchant.
/// @param bAll TRUE to list the ones above their level too; those come back
///     flagged and the window locks them.
/// @returns Rows "id|section|name|dc|level|reachable", separated by ';'.
string CnrArc_ListProperties(object oPC, int iBaseItem, int bAll = FALSE);

/// @brief The data of one property.
/// @param iArcaneId Identifier from cnr_arcane_property.
/// @returns "section|name|group|tier|essence|crystal|type|subtype|level|dc|
///     essenceName|crystalName|source|dcEntry|dcTop", or empty when it does
///     not exist.
///
/// Field 9 is the property's raw dc and is what the design authored. Fields 13
/// and 14 are the DCs the player actually rolls against for the first and the
/// last step, which is what anything user-facing should read: the raw dc is no
/// longer the entry once the ceiling pulls a long ladder down.
string CnrArc_ReadProperty(int iArcaneId);

/// @brief The steps of a property, to fill the amount selector.
/// @param iArcaneId Identifier from cnr_arcane_property.
/// @returns Rows "essences|label|dc", separated by ';'. The DC is the one that
///     step is rolled against, so the selector can price the choice before the
///     player commits to it.
string CnrArc_ListSteps(int iArcaneId);

/// @brief The data of one step.
/// @param iArcaneId The property.
/// @param iEssences How many essences the player wants to spend.
/// @returns "subtype|value1|value2|xp|label|dc", or empty when that step does
///     not exist. A missing step is the signal that the request is not legal.
///
/// Field 5 is the DC to roll against, and it is the property's entry DC plus
/// one per extra rung - the step's place in the ladder, never the essences it
/// costs, since half the ladders skip essence counts. Read it from here and
/// never from the property's own dc: that column is the design's authored
/// number, not what this step costs.
string CnrArc_ReadStep(int iArcaneId, int iEssences);

/// @brief Does this group accept that base item type?
/// @param iGroup Group identifier.
/// @param iBaseItem BASE_ITEM_* value.
/// @returns How many crystals it costs, or 0 when the group refuses it. The
///     "any" group accepts everything and costs one.
int CnrArc_CrystalCost(int iGroup, int iBaseItem);

/// @brief What is missing before this can be enchanted, ready for the chat.
/// @param oPC The crafter.
/// @param oTable The station placeable.
/// @param iArcaneId The chosen property.
/// @param iEssences The chosen step.
/// @returns One line per missing material with its count; empty when nothing
///     is missing.
string CnrArc_Missing(object oPC, object oTable, int iArcaneId, int iEssences);

// -----------------------------------------------------------------------------
//                             Function Definitions
// -----------------------------------------------------------------------------

string CnrArc_Field(string sRow, int iIndex)
{
    string sRest = sRow;
    int i;
    for (i = 0; i < iIndex; i++)
    {
        int iCut = FindSubString(sRest, CNR_ARC_SEP_FIELD);
        if (iCut < 0)
        {
            return "";
        }
        sRest = GetStringRight(sRest, GetStringLength(sRest) - iCut - 1);
    }
    int iEnd = FindSubString(sRest, CNR_ARC_SEP_FIELD);
    return (iEnd < 0) ? sRest : GetStringLeft(sRest, iEnd);
}

int CnrArc_IsEnchantable(object oItem)
{
    if (!GetIsObjectValid(oItem))
    {
        return FALSE;
    }
    if (GetLocalInt(oItem, CNR_ARC_VAR_DONE))
    {
        return FALSE;
    }
    return GetLocalInt(oItem, CNR_ARC_VAR_TRADE) > 0;
}

int CnrArc_TargetState(object oTable)
{
    int iValid = 0;
    int iDone  = 0;

    object oItem = GetFirstItemInInventory(oTable);
    while (GetIsObjectValid(oItem))
    {
        if (GetLocalInt(oItem, CNR_ARC_VAR_TRADE) > 0)
        {
            if (GetLocalInt(oItem, CNR_ARC_VAR_DONE))
            {
                iDone++;
            }
            else
            {
                iValid++;
            }
        }
        oItem = GetNextItemInInventory(oTable);
    }

    if (iValid == 1)
    {
        return CNR_ARC_TARGET_OK;
    }
    if (iValid > 1)
    {
        return CNR_ARC_TARGET_MANY;
    }
    if (iDone > 0)
    {
        return CNR_ARC_TARGET_DONE;
    }
    return CNR_ARC_TARGET_NONE;
}

object CnrArc_GetTarget(object oTable)
{
    // Only returns something when there is exactly one. With two inside,
    // choosing for the player is the fastest way to enchant the wrong item.
    if (CnrArc_TargetState(oTable) != CNR_ARC_TARGET_OK)
    {
        return OBJECT_INVALID;
    }

    object oItem = GetFirstItemInInventory(oTable);
    while (GetIsObjectValid(oItem))
    {
        if (CnrArc_IsEnchantable(oItem))
        {
            return oItem;
        }
        oItem = GetNextItemInInventory(oTable);
    }
    return OBJECT_INVALID;
}

int CnrArc_CountMaterial(object oTable, string sTag)
{
    int iTotal = 0;
    object oItem = GetFirstItemInInventory(oTable);
    while (GetIsObjectValid(oItem))
    {
        if (GetTag(oItem) == sTag)
        {
            int iStack = GetItemStackSize(oItem);
            iTotal += (iStack > 0) ? iStack : 1;
        }
        oItem = GetNextItemInInventory(oTable);
    }
    return iTotal;
}

int CnrArc_GetLevel(object oPC)
{
    return CnrSkill_GetLevel(oPC, CNR_ARC_SKILL);
}

string CnrArc_SqlStepCount()
{
    return "GREATEST((SELECT COUNT(*) FROM cnr_arcane_step x"
         + " WHERE x.arcane_id = p.arcane_id), 1)";
}

string CnrArc_SqlStepRank()
{
    return "(SELECT COUNT(*) FROM cnr_arcane_step y"
         + " WHERE y.arcane_id = s.arcane_id AND y.essences <= s.essences)";
}

string CnrArc_SqlEntryDC()
{
    // LEAST clamps the entry, never the rung. Clamping the rung would repeat a
    // DC at the top of a long ladder, and every rung has to differ.
    return "LEAST(p.dc, " + IntToString(CNR_ARC_DC_CEILING) + " - ("
         + CnrArc_SqlStepCount() + " - 1))";
}

string CnrArc_ListProperties(object oPC, int iBaseItem, int bAll)
{
    int iLevel = CnrArc_GetLevel(oPC);

    // supported = 0 means no consumer knows how to apply that type: the roll
    // would succeed and the item would come back empty, so those are never
    // offered, not even under "show everything".
    if (!NWNX_SQL_PrepareQuery(
        "SELECT p.arcane_id, p.section, p.display_name, p.dc, p.min_level,"
        + "       (p.min_level <= ?) AS reachable"
        + " FROM cnr_arcane_property p"
        + " JOIN cnr_arcane_group g ON g.group_id = p.group_id"
        + " LEFT JOIN cnr_arcane_group_base b"
        + "   ON b.group_id = p.group_id AND b.base_item = ?"
        + " WHERE p.supported = 1 AND (? = 1 OR p.min_level <= ?)"
        + "   AND (g.any_base = 1 OR b.base_item IS NOT NULL)"
        + " ORDER BY p.section, p.min_level, p.display_name"))
    {
        return "";
    }

    NWNX_SQL_PreparedInt(0, iLevel);
    NWNX_SQL_PreparedInt(1, iBaseItem);
    NWNX_SQL_PreparedInt(2, bAll);
    NWNX_SQL_PreparedInt(3, iLevel);

    if (!NWNX_SQL_ExecutePreparedQuery())
    {
        return "";
    }

    string sOut = "";
    while (NWNX_SQL_ReadyToReadNextRow())
    {
        NWNX_SQL_ReadNextRow();
        sOut += NWNX_SQL_ReadDataInActiveRow(0) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(1) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(2) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(3) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(4) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(5) + CNR_ARC_SEP_ROW;
    }
    return sOut;
}

string CnrArc_ReadProperty(int iArcaneId)
{
    if (!NWNX_SQL_PrepareQuery(
        "SELECT p.section, p.display_name, p.group_id, p.tier,"
        + "       p.essence_resref, p.crystal_resref, p.property_type,"
        + "       p.subtype, p.min_level, p.dc,"
        + "       p.essence_name, p.crystal_name, p.ubicacion,"
        + "       " + CnrArc_SqlEntryDC() + ","
        + "       " + CnrArc_SqlEntryDC() + " + " + CnrArc_SqlStepCount()
        + " - 1"
        + " FROM cnr_arcane_property p"
        + " WHERE p.arcane_id = ? AND p.supported = 1"
        + " LIMIT 1"))
    {
        return "";
    }

    NWNX_SQL_PreparedInt(0, iArcaneId);

    if (!NWNX_SQL_ExecutePreparedQuery() || !NWNX_SQL_ReadyToReadNextRow())
    {
        return "";
    }

    NWNX_SQL_ReadNextRow();
    return NWNX_SQL_ReadDataInActiveRow(0) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(1) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(2) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(3) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(4) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(5) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(6) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(7) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(8) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(9) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(10) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(11) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(12) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(13) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(14);
}

string CnrArc_ListSteps(int iArcaneId)
{
    if (!NWNX_SQL_PrepareQuery(
        "SELECT s.essences, s.display_value,"
        + "       " + CnrArc_SqlEntryDC() + " + " + CnrArc_SqlStepRank() + " - 1"
        + " FROM cnr_arcane_step s"
        + " JOIN cnr_arcane_property p ON p.arcane_id = s.arcane_id"
        + " WHERE s.arcane_id = ? ORDER BY s.essences"))
    {
        return "";
    }

    NWNX_SQL_PreparedInt(0, iArcaneId);

    if (!NWNX_SQL_ExecutePreparedQuery())
    {
        return "";
    }

    string sOut = "";
    while (NWNX_SQL_ReadyToReadNextRow())
    {
        NWNX_SQL_ReadNextRow();
        sOut += NWNX_SQL_ReadDataInActiveRow(0) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(1) + CNR_ARC_SEP_FIELD
              + NWNX_SQL_ReadDataInActiveRow(2) + CNR_ARC_SEP_ROW;
    }
    return sOut;
}

string CnrArc_ReadStep(int iArcaneId, int iEssences)
{
    // That the step exists is the whole validation of the value: the window
    // can ask for "+7 with one essence" and there is simply no row for it.
    if (!NWNX_SQL_PrepareQuery(
        "SELECT IFNULL(s.subtype, -1), s.value1, s.value2, s.xp,"
        + "       s.display_value,"
        + "       " + CnrArc_SqlEntryDC() + " + " + CnrArc_SqlStepRank() + " - 1"
        + " FROM cnr_arcane_step s"
        + " JOIN cnr_arcane_property p ON p.arcane_id = s.arcane_id"
        + " WHERE s.arcane_id = ? AND s.essences = ? LIMIT 1"))
    {
        return "";
    }

    NWNX_SQL_PreparedInt(0, iArcaneId);
    NWNX_SQL_PreparedInt(1, iEssences);

    if (!NWNX_SQL_ExecutePreparedQuery() || !NWNX_SQL_ReadyToReadNextRow())
    {
        return "";
    }

    NWNX_SQL_ReadNextRow();
    return NWNX_SQL_ReadDataInActiveRow(0) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(1) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(2) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(3) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(4) + CNR_ARC_SEP_FIELD
         + NWNX_SQL_ReadDataInActiveRow(5);
}

int CnrArc_CrystalCost(int iGroup, int iBaseItem)
{
    if (!NWNX_SQL_PrepareQuery(
        "SELECT g.any_base, IFNULL(b.crystal_cost, 0)"
        + " FROM cnr_arcane_group g"
        + " LEFT JOIN cnr_arcane_group_base b"
        + "   ON b.group_id = g.group_id AND b.base_item = ?"
        + " WHERE g.group_id = ? LIMIT 1"))
    {
        return 0;
    }

    NWNX_SQL_PreparedInt(0, iBaseItem);
    NWNX_SQL_PreparedInt(1, iGroup);

    if (!NWNX_SQL_ExecutePreparedQuery() || !NWNX_SQL_ReadyToReadNextRow())
    {
        return 0;
    }

    NWNX_SQL_ReadNextRow();
    int iAnyBase = StringToInt(NWNX_SQL_ReadDataInActiveRow(0));
    int iCost    = StringToInt(NWNX_SQL_ReadDataInActiveRow(1));

    if (iAnyBase)
    {
        return 1;
    }
    return iCost;
}

string CnrArc_Missing(object oPC, object oTable, int iArcaneId, int iEssences)
{
    string sProperty = CnrArc_ReadProperty(iArcaneId);
    if (sProperty == "")
    {
        return "Esa propiedad no existe o no se puede aplicar.";
    }

    if (CnrArc_ReadStep(iArcaneId, iEssences) == "")
    {
        return "Esa cantidad de esencias no compra ningun valor.";
    }

    int    iGroup       = StringToInt(CnrArc_Field(sProperty, 2));
    string sEssence     = CnrArc_Field(sProperty, 4);
    string sCrystal     = CnrArc_Field(sProperty, 5);
    string sEssenceName = CnrArc_Field(sProperty, 10);
    string sCrystalName = CnrArc_Field(sProperty, 11);

    object oTarget = CnrArc_GetTarget(oTable);
    if (!GetIsObjectValid(oTarget))
    {
        return "Pon en la mesa un solo objeto de oficio sin encantar.";
    }

    int iCrystals = CnrArc_CrystalCost(iGroup, GetBaseItemType(oTarget));
    if (iCrystals <= 0)
    {
        return "Ese objeto no admite esta propiedad.";
    }

    int iHaveEssence = CnrArc_CountMaterial(oTable, sEssence);
    int iHaveCrystal = CnrArc_CountMaterial(oTable, sCrystal);

    string sMissing = "";
    if (iHaveEssence < iEssences)
    {
        sMissing += sEssenceName + " " + IntToString(iHaveEssence) + "/"
                  + IntToString(iEssences);
    }
    if (iHaveCrystal < iCrystals)
    {
        if (sMissing != "")
        {
            sMissing += "\n";
        }
        sMissing += sCrystalName + " " + IntToString(iHaveCrystal) + "/"
                  + IntToString(iCrystals);
    }
    return sMissing;
}
