/// ----------------------------------------------------------------------------
/// @system  CNR Almacen
/// @file    sapo_cons_alma
/// @author  Monti
/// @brief   The ingredient list of the material store: what it accepts, under
///          which persistent key each quantity is kept, and how each line is
///          named to the player.
///
///          Three parallel arrays, one index per material:
///            sTagIngOficio  the blueprint RESREF. CreateItemOnObject is given
///                           this, so it must be the file name, never the tag:
///                           a resref is capped at 16 characters and a tag is
///                           not, and five materials used to differ.
///            sVarIngOficio  the key the quantity lives under, on the player's
///                           own variable container. **Never rename one of
///                           these**: the name is the only thing tying a player
///                           to what they have stored.
///            sNomIngOficio  the line the player reads, ending in ": ".
///
///          Only raw node output and materials produced at a station belong
///          here. Nothing equippable, nothing bought in a shop, no tool and no
///          potion: the store keeps a count and not the item, so anything
///          carrying its own properties would come back stripped of them.
/// modified by: Dhraax
/// ----------------------------------------------------------------------------

#include "nw_o0_itemmaker"

const int NUM_DIST_INGRED = 281;

void CargaArray(object oUbicado)
{
  SetLocalArrayString(oUbicado, "sTagIngOficio", 1, "cnr_e_117");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 1, "cnr_e_117");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 1, "Aletas de locathah: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 2, "cnr_e_38");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 2, "cnr_e_38");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 2, "Aleteo de sagifalco juvenil: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 3, "bru_amar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 3, "bru_amar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 3, "Amarazha en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 4, "cnr_amar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 4, "cnr_amar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 4, "Amarazha tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 5, "bru_per");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 5, "bru_per");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 5, "Amatista en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 6, "cnr_per");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 6, "cnr_per");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 6, "Amatista tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 7, "cnr_e_2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 7, "cnr_e_2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 7, "Antenas de grilio: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 8, "ardordesertico");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 8, "ardordesertico");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 8, "Ardores desérticos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 9, "cnr_e_113");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 9, "cnr_e_113");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 9, "Armazón de siv: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 10, "cnr_e_32");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 10, "cnr_e_32");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 10, "Astucia de arpía: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 11, "cnr_e_62");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 11, "cnr_e_62");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 11, "Astucia de márilith: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 12, "cnr_aza");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 12, "cnr_aza");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 12, "Azabache tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 13, "bru_barra");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 13, "bru_barra");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 13, "Barra lunar en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 14, "cnr_barra");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 14, "cnr_barra");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 14, "Barra lunar tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 15, "bayaacuosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 15, "bayaacuosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 15, "Bayas acuosas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 16, "bru_bel");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 16, "bru_bel");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 16, "Beljuril en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 17, "cnr_bel");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 17, "cnr_bel");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 17, "Beljuril tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 18, "cnr_e_18");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 18, "cnr_e_18");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 18, "Belleza cegadora de ninfa: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 19, "cnr_e_112");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 19, "cnr_e_112");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 19, "Belleza sobrenatural de clangarconte: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 20, "cnr_e_1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 20, "cnr_e_1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 20, "Bolsa viscosa de bestia del caos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 21, "cnr_e_126");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 21, "cnr_e_126");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 21, "Brasas de azer: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 22, "cnr_e_39");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 22, "cnr_e_39");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 22, "Brillo de magmino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 23, "brisasusurrante");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 23, "brisasusurrante");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 23, "Brisas susurrantes: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 24, "cnr_e_11");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 24, "cnr_e_11");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 24, "Cabello de ghaele: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 25, "cnr_e_24");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 25, "cnr_e_24");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 25, "Cadenas de kiton: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 26, "cnr_e_44");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 26, "cnr_e_44");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 26, "Calima de zombi de bruma tirana: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 27, "cnr_e_31");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 27, "cnr_e_31");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 27, "Caparazón de ankheg: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 28, "cnr_e_45");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 28, "cnr_e_45");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 28, "Carne pegajosa de regresado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 29, "cnr_e_84");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 29, "cnr_e_84");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 29, "Carne putrefacta del señor de las momias: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 30, "cnr_e_91");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 30, "cnr_e_91");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 30, "Carroña de xorn: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 31, "cnr_e_72");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 31, "cnr_e_72");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 31, "Caspa de ibrandlin: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 32, "cnr_e_21");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 32, "cnr_e_21");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 32, "Castigo de nálfeshni: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 33, "cnr_e_95");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 33, "cnr_e_95");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 33, "Cataclismo de tarasca: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 34, "cnr_e_67");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 34, "cnr_e_67");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 34, "Claridad de nyzh: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 35, "cnr_e_64");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 35, "cnr_e_64");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 35, "Colmillo de abishái: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 36, "cnr_e_96");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 36, "cnr_e_96");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 36, "Concentración de diablo astado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 37, "cnr_e_26");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 37, "cnr_e_26");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 37, "Concha de tojánida: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 38, "cnr_e_41");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 38, "cnr_e_41");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 38, "Consunción de incorpóreo aterrador: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 39, "cnr_e_111");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 39, "cnr_e_111");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 39, "Contrato de kolyarut: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 40, "cnr_e_4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 40, "cnr_e_4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 40, "Corazón negro de pesadilla: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 41, "cnr_e_48");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 41, "cnr_e_48");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 41, "Cornadura de unicornio negro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 42, "cnr_e_116");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 42, "cnr_e_116");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 42, "Corteza de árbol oscuro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 43, "bru_cor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 43, "bru_cor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 43, "Corvidar en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 44, "cnr_cor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 44, "cnr_cor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 44, "Corvidar tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 45, "cnr_e_17");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 45, "cnr_e_17");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 45, "Cresta de dragón tortuga: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 46, "bru_aza");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 46, "bru_aza");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 46, "Cristal de azabache en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 47, "cnr_c_5");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 47, "cnr_c_5");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 47, "Cristal urdímbrico de Contemplador: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 48, "cnr_c_4");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 48, "cnr_c_4");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 48, "Cristal urdímbrico de Dragón: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 49, "cnr_c_2");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 49, "cnr_c_2");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 49, "Cristal urdímbrico de Fénix: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 50, "cnr_c_3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 50, "cnr_c_3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 50, "Cristal urdímbrico de Hada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 51, "cnr_c_1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 51, "cnr_c_1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 51, "Cristal urdímbrico de Nishruu: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 52, "cnr_c_6");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 52, "cnr_c_6");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 52, "Cristal urdímbrico de Sombra: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 53, "cnr_e_98");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 53, "cnr_e_98");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 53, "Crueldad de lamia: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 54, "bru_cuarzo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 54, "bru_cuarzo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 54, "Cuarzo hialino en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 55, "cnr_cuarzo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 55, "cnr_cuarzo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 55, "Cuarzo hialino tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 56, "cnr_e_94");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 56, "cnr_e_94");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 56, "Cuerno de behir: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 57, "cuero_bestiag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 57, "cuero_bestiag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 57, "Cuero de Bestia Grande: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 58, "cuero_miticag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 58, "cuero_miticag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 58, "Cuero de Bestia Mitica Grande: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 59, "cuero_mitica");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 59, "cuero_mitica");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 59, "Cuero de Bestia Mitica: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 60, "cuero_bestia");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 60, "cuero_bestia");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 60, "Cuero de Bestia: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 61, "cuero_dragoa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 61, "cuero_dragoa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 61, "Cuero de Dragon de Acido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 62, "cuero_dragof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 62, "cuero_dragof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 62, "Cuero de Dragon de Fuego: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 63, "cuero_dragoh");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 63, "cuero_dragoh");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 63, "Cuero de Dragon de Hielo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 64, "cuero_dragor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 64, "cuero_dragor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 64, "Cuero de Dragon de Rayo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 65, "cuero_herbivoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 65, "cuero_herbivoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 65, "Cuero de Herbivoro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 66, "cuero_roedor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 66, "cuero_roedor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 66, "Cuero de Roedor: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 67, "cnr_e_114");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 67, "cnr_e_114");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 67, "Cáscara de batraco: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 68, "cnr_e_42");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 68, "cnr_e_42");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 68, "Deambulamiento de rávido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 69, "cnr_e_30");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 69, "cnr_e_30");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 69, "Dentina de bestia oscurecida: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 70, "cnr_e_129");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 70, "cnr_e_129");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 70, "Derribo de sabueso yez: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 71, "cnr_e_35");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 71, "cnr_e_35");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 71, "Descomposición de broza movediza: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 72, "cnr_e_51");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 72, "cnr_e_51");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 72, "Devoción de mártir: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 73, "bru_diam");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 73, "bru_diam");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 73, "Diamante en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 74, "cnr_diam");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 74, "cnr_diam");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 74, "Diamante tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 75, "cnr_e_50");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 75, "cnr_e_50");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 75, "Dádiva de archiliche: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 76, "cnr_e_15");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 76, "cnr_e_15");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 76, "Elasticidad de fasmo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 77, "cnr_e_34");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 77, "cnr_e_34");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 77, "Encanto de dríada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 78, "cnr_e_52");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 78, "cnr_e_52");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 78, "Encanto de lilenda: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 79, "cnr_e_53");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 79, "cnr_e_53");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 79, "Enigma de ginoesfinge: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 80, "cnr_e_69");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 80, "cnr_e_69");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 80, "Escama de asabi: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 81, "esenciainvisible");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 81, "esenciainvisible");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 81, "Esencias invisibles: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 82, "bru_esme");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 82, "bru_esme");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 82, "Esmeralda en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 83, "cnr_esme");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 83, "cnr_esme");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 83, "Esmeralda tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 84, "especiasulfurosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 84, "especiasulfurosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 84, "Especias sulfurosas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 85, "cnr_e_46");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 85, "cnr_e_46");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 85, "Espectro de réprobo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 86, "cnr_e_66");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 86, "cnr_e_66");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 86, "Espolón de dragónido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 87, "cnr_e_99");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 87, "cnr_e_99");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 87, "Estallido de diablo de la sima: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 88, "cnr_e_23");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 88, "cnr_e_23");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 88, "Estragos de quimera: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 89, "cnr_e_40");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 89, "cnr_e_40");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 89, "Eteriedad de serpiente de hielo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 90, "cnr_e_5");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 90, "cnr_e_5");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 90, "Excrecencia ósea de abolez mago: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 91, "cnr_e_74");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 91, "cnr_e_74");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 91, "Faz de hybsil: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 92, "cnr_e_60");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 92, "cnr_e_60");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 92, "Ferocidad de erinia: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 93, "cnr_e_54");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 93, "cnr_e_54");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 93, "Fervor de ent: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 94, "cnr_e_7");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 94, "cnr_e_7");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 94, "Firmeza de titán: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 95, "cnr_e_6");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 95, "cnr_e_6");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 95, "Flautín de sátiro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 96, "florluminosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 96, "florluminosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 96, "Flores luminosas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 97, "cnr_e_102");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 97, "cnr_e_102");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 97, "Fragmento de gólem de amatista: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 98, "cnr_e_105");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 98, "cnr_e_105");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 98, "Fragmento de gólem de citrino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 99, "cnr_e_106");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 99, "cnr_e_106");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 99, "Fragmento de gólem de diamante: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 100, "cnr_e_104");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 100, "cnr_e_104");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 100, "Fragmento de gólem de esmeralda: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 101, "cnr_e_103");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 101, "cnr_e_103");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 101, "Fragmento de gólem de rubí: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 102, "cnr_e_101");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 102, "cnr_e_101");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 102, "Fragmento de gólem de topacio: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 103, "cnr_e_100");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 103, "cnr_e_100");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 103, "Fragmento de gólem de zafiro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 104, "frutofantasma");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 104, "frutofantasma");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 104, "Frutos fantasma: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 105, "sute_her_fr1");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 105, "sute_her_fr1");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 105, "Galleta mágica: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 106, "cnr_e_89");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 106, "cnr_e_89");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 106, "Galope de centauro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 107, "cnr_e_81");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 107, "cnr_e_81");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 107, "Gas de dragón de oropel: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 108, "cnr_e_70");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 108, "cnr_e_70");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 108, "Gotas de ábalin: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 109, "cnr_e_27");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 109, "cnr_e_27");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 109, "Gracia de sirénido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 110, "humogaseoso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 110, "humogaseoso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 110, "Humos gaseosos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 111, "cnr_e_68");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 111, "cnr_e_68");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 111, "Hálito de dragón del canto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 112, "cnr_e_55");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 112, "cnr_e_55");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 112, "Instinto de lobo terrible: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 113, "cnr_e_14");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 113, "cnr_e_14");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 113, "Instrucciones telepáticas de formícida reina: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 114, "bru_jac");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 114, "bru_jac");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 114, "Jacinto en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 115, "cnr_jac");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 115, "cnr_jac");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 115, "Jacinto tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 116, "bru_jade");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 116, "bru_jade");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 116, "Jade de tumba en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 117, "cnr_jade");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 117, "cnr_jade");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 117, "Jade de tumba tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 118, "cnr_e_36");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 118, "cnr_e_36");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 118, "Lengua bífida de Yuan-ti: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 119, "cnr_e_92");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 119, "cnr_e_92");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 119, "Levitación de lamparconte: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 120, "carplenyo_abeto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 120, "lenyoabeto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 120, "Leños de abeto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 121, "carplenyo_cedro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 121, "lenyocedro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 121, "Leños de cedro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 122, "carplenyo_cipres");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 122, "lenyocipres");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 122, "Leños de ciprés: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 123, "carplenyo_fresno");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 123, "lenyofresno");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 123, "Leños de fresno: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 124, "carplenyo_olmo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 124, "lenyoolmo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 124, "Leños de olmo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 125, "carplenyo_pino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 125, "lenyopino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 125, "Leños de pino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 126, "carplenyo_roble");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 126, "lenyoroble");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 126, "Leños de roble: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 127, "carplenyo_alamo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 127, "lenyoalamo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 127, "Leños de álamo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 128, "limoputrefacto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 128, "limoputrefacto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 128, "Limos putrefactos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 129, "lingoteaceroscur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 129, "lingoteaceroscur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 129, "Lingote de aceroscuro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 130, "lingoteadamantit");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 130, "lingoteadamantit");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 130, "Lingote de adamantita: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 131, "lingotearandur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 131, "lingoteArandur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 131, "Lingote de arandur: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 132, "lingotedlarun");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 132, "lingoteDlarun");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 132, "Lingote de dlarun: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 133, "lingotederretido");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 133, "lingoteDerretido");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 133, "Lingote de hierro enardecido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 134, "lingotehierrofri");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 134, "lingotehierrofri");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 134, "Lingote de hierrofrío: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 135, "lingotehizagkuur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 135, "lingoteHizagkuur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 135, "Lingote de hizagkuur: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 136, "lingotemetalvivo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 136, "lingoteMetalvivo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 136, "Lingote de metal vivo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 137, "lingoteplatino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 137, "lingotePlatino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 137, "Lingote de platino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 138, "lingoteacero");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 138, "lingoteacero");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 138, "Lingotes de acero: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 139, "lingotecobre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 139, "lingotecobre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 139, "Lingotes de cobre: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 140, "lingotehierro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 140, "lingotehierro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 140, "Lingotes de hierro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 141, "lingotemithril");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 141, "lingotemithril");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 141, "Lingotes de mithril: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 142, "lingoteoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 142, "lingoteoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 142, "Lingotes de oro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 143, "lingoteplata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 143, "lingoteplata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 143, "Lingotes de plata: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 144, "cnr_e_49");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 144, "cnr_e_49");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 144, "Liviandad de béstia de Xvim: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 145, "cnr_e_108");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 145, "cnr_e_108");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 145, "Locura de derro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 146, "cnr_e_107");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 146, "cnr_e_107");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 146, "Luz carmesí de liche: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 147, "cnr_e_90");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 147, "cnr_e_90");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 147, "Luz cegadora de bezekira: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 148, "bru_lagrey");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 148, "bru_lagrey");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 148, "Lágrima del rey en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 149, "cnr_lagrey");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 149, "cnr_lagrey");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 149, "Lágrima del rey tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 150, "bru_lagrimar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 150, "bru_lagrimar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 150, "Lágrima roja en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 151, "cnr_lagrimar");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 151, "cnr_lagrimar");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 151, "Lágrima roja tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 152, "cnr_e_76");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 152, "cnr_e_76");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 152, "Mandíbula de aranea: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 153, "cnr_e_87");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 153, "cnr_e_87");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 153, "Mordisco de perro de guerra nessiano: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 154, "cnr_e_9");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 154, "cnr_e_9");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 154, "Mudez de birlador etéreo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 155, "cnr_e_25");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 155, "cnr_e_25");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 155, "Músculos de planotáreo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 156, "cnr_e_57");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 156, "cnr_e_57");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 156, "Nobleza de grifo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 157, "bru_obs");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 157, "bru_obs");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 157, "Obsidiana en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 158, "cnr_obs");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 158, "cnr_obs");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 158, "Obsidiana tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 159, "cnr_e_75");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 159, "cnr_e_75");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 159, "Ojo de contemplador: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 160, "cnr_e_47");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 160, "cnr_e_47");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 160, "Ojo oscuro carmesí de tritón de fuego: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 161, "cnr_e_33");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 161, "cnr_e_33");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 161, "Ojos rojos de medusa: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 162, "bru_orblen");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 162, "bru_orblen");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 162, "Orblen en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 163, "cnr_orblen");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 163, "cnr_orblen");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 163, "Orblen tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 164, "bru_orlo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 164, "bru_orlo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 164, "Orlo en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 165, "cnr_orlo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 165, "cnr_orlo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 165, "Orlo tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 166, "pastaterrosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 166, "pastaterrosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 166, "Pastas terrosas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 167, "cnr_e_110");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 167, "cnr_e_110");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 167, "Pata zancuda de aquerena: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 168, "cnr_e_71");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 168, "cnr_e_71");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 168, "Pelaje de araña subterránea: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 169, "pepitaarandur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 169, "pepitaArandur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 169, "Pepita de arandur: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 170, "pepitacarbon");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 170, "pepitaCarbon");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 170, "Pepita de carbón: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 171, "pepitadlarun");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 171, "pepitaDlarun");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 171, "Pepita de dlarun: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 172, "pepitaaceroscuro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 172, "pepitaAceroscuro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 172, "Pepita de hierro meteórico: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 173, "pepitahizagkuur");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 173, "pepitaHizagkuur");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 173, "Pepita de hizagkuur: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 174, "pepitaderretido");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 174, "pepitaDerretido");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 174, "Pepita de metal derretido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 175, "pepitametalvivo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 175, "pepitaMetalvivo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 175, "Pepita de metal vivo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 176, "pepitaplatino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 176, "pepitaPlatino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 176, "Pepita de platino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 177, "pepitaacero");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 177, "pepitaacero");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 177, "Pepitas de acero: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 178, "pepitaadamantita");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 178, "pepitaadamantita");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 178, "Pepitas de adamantita: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 179, "pepitacobre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 179, "pepitacobre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 179, "Pepitas de cobre: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 180, "pepitahierro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 180, "pepitahierro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 180, "Pepitas de hierro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 181, "pepitahierrofrio");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 181, "pepitahierrofrio");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 181, "Pepitas de hierrofrío: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 182, "pepitamithril");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 182, "pepitamithril");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 182, "Pepitas de mithril: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 183, "pepitaoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 183, "pepitaoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 183, "Pepitas de oro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 184, "pepitaplata");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 184, "pepitaplata");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 184, "Pepitas de plata: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 185, "cnr_e_63");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 185, "cnr_e_63");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 185, "Pesuño de bestia de Málar: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 186, "cnr_e_20");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 186, "cnr_e_20");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 186, "Pezuña de pegaso: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 187, "picadarocosa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 187, "picadarocosa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 187, "Picadas rocosas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 188, "cnr_e_12");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 188, "cnr_e_12");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 188, "Pico de águila gigante: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 189, "bru_picara");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 189, "bru_picara");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 189, "Piedra pícara en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 190, "cnr_picara");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 190, "cnr_picara");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 190, "Piedra pícara tallada: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 191, "cnr_e_93");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 191, "cnr_e_93");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 191, "Piel correosa de troll cazador: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 192, "pielbestiag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 192, "pielbestiag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 192, "Piel de Bestia Grande: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 193, "pielmiticag");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 193, "pielmiticag");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 193, "Piel de bestia mitica Grande: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 194, "pielmitica");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 194, "pielmitica");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 194, "Piel de bestia mitica: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 195, "pielbestia");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 195, "pielbestia");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 195, "Piel de Bestia: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 196, "pieldracoa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 196, "pieldracoa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 196, "Piel de Dragon de Acido: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 197, "pieldracof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 197, "pieldracof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 197, "Piel de Dragon de Fuego: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 198, "pieldracoh");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 198, "pieldracoh");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 198, "Piel de Dragon de Hielo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 199, "pieldracor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 199, "pieldracor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 199, "Piel de Dragon de Rayo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 200, "pielherbivoro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 200, "pielherbivoro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 200, "Piel de Hervivoro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 201, "pielroedor");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 201, "pielroedor");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 201, "Piel de Roedor: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 202, "cnr_e_22");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 202, "cnr_e_22");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 202, "Pigmentación de mimeto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 203, "cnr_e_109");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 203, "cnr_e_109");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 203, "Pinzas de glabrezu: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 204, "cnr_e_77");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 204, "cnr_e_77");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 204, "Plaga de murciélagos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 205, "cnr_e_115");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 205, "cnr_e_115");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 205, "Plumas de aarakocra: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 206, "cnr_e_56");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 206, "cnr_e_56");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 206, "Plumas de couatl: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 207, "cnr_e_8");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 207, "cnr_e_8");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 207, "Plumazón de roc: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 208, "cnr_e_28");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 208, "cnr_e_28");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 208, "Podredumbre de babau: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 209, "cnr_e_118");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 209, "cnr_e_118");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 209, "Polvo de abjuración: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 210, "cnr_e_120");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 210, "cnr_e_120");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 210, "Polvo de adivinación: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 211, "cnr_e_119");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 211, "cnr_e_119");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 211, "Polvo de conjuración: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 212, "cnr_e_121");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 212, "cnr_e_121");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 212, "Polvo de encantamiento: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 213, "cnr_e_122");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 213, "cnr_e_122");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 213, "Polvo de evocación: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 214, "cnr_e_123");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 214, "cnr_e_123");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 214, "Polvo de ilusión: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 215, "cnr_e_124");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 215, "cnr_e_124");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 215, "Polvo de nigromancia: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 216, "cnr_e_125");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 216, "cnr_e_125");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 216, "Polvo de transmutación: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 217, "cnr_e_13");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 217, "cnr_e_13");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 217, "Presa de búho gigante: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 218, "cnr_e_78");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 218, "cnr_e_78");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 218, "Presa de gusano púrpura: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 219, "cnr_e_10");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 219, "cnr_e_10");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 219, "Protección de solar: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 220, "cnr_e_79");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 220, "cnr_e_79");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 220, "Puño de trueno de marut: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 221, "cnr_e_88");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 221, "cnr_e_88");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 221, "Púa afilada de gelugón: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 222, "cnr_e_3");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 222, "cnr_e_3");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 222, "Púas de salamandra: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 223, "raizpetrea");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 223, "raizpetrea");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 223, "Raíces pétreas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 224, "resinasubterrane");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 224, "resinasubterrane");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 224, "Resina Subterránea: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 225, "cnr_e_37");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 225, "cnr_e_37");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 225, "Resistencia de slaad: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 226, "cnr_e_127");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 226, "cnr_e_127");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 226, "Restos de un objeto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 227, "bru_rubi");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 227, "bru_rubi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 227, "Rubí en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 228, "bru_rubiestre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 228, "bru_rubiestre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 228, "Rubí estrella en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 229, "cnr_rubiestre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 229, "cnr_rubiestre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 229, "Rubí estrella tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 230, "cnr_rubi");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 230, "cnr_rubi");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 230, "Rubí tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 231, "cnr_e_86");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 231, "cnr_e_86");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 231, "Sangre de vampiro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 232, "polvo_per");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 232, "polvoper");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 232, "Saquitos de arenilla de amatista: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 233, "polvo_aza");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 233, "polvoaza");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 233, "Saquitos de arenilla de azabache: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 234, "polvo_cua");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 234, "polvocua");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 234, "Saquitos de arenilla de cuarzo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 235, "polvo_obs");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 235, "polvoobs");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 235, "Saquitos de arenilla de obsidiana: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 236, "polvo_rub");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 236, "polvorub");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 236, "Saquitos de arenilla de rubí: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 237, "polvo_top");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 237, "polvotop");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 237, "Saquitos de arenilla de topacio: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 238, "polvo_zaf");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 238, "polvozaf");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 238, "Saquitos de arenilla de zafiro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 239, "setanocturna");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 239, "setanocturna");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 239, "Setas nocturnas: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 240, "cnr_e_19");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 240, "cnr_e_19");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 240, "Silueta serpentiforme de behir: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 241, "cnr_e_16");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 241, "cnr_e_16");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 241, "Siseo de ahogador: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 242, "carptablon_abeto");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 242, "tablonabeto");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 242, "Tablones de abeto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 243, "carptablon_cedro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 243, "tabloncedro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 243, "Tablones de cedro: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 244, "carptablon_cipre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 244, "tabloncipres");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 244, "Tablones de ciprés: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 245, "carptablon_fresn");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 245, "tablonfresno");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 245, "Tablones de fresno: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 246, "carptablon_olmo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 246, "tablonolmo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 246, "Tablones de olmo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 247, "carptablon_pino");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 247, "tablonpino");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 247, "Tablones de pino: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 248, "carptablon_roble");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 248, "tablonroble");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 248, "Tablones de roble: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 249, "carptablon_alamo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 249, "tablonalamo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 249, "Tablones de álamo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 250, "cnr_e_73");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 250, "cnr_e_73");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 250, "Tentáculo de yokhol: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 251, "cnr_e_43");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 251, "cnr_e_43");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 251, "Tez de Fee'ri: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 252, "cnr_e_59");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 252, "cnr_e_59");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 252, "Tinieblas de noctámbulo: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 253, "bru_top");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 253, "bru_top");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 253, "Topacio en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 254, "cnr_top");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 254, "cnr_top");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 254, "Topacio tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 255, "cnr_e_61");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 255, "cnr_e_61");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 255, "Tutelaje de deva astral: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 256, "cnr_e_65");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 256, "cnr_e_65");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 256, "Vellosidad de alaghi: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 257, "cnr_e_85");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 257, "cnr_e_85");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 257, "Verruga de saga nocturna: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 258, "virutasresplande");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 258, "virutasresplande");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 258, "Virutas Resplandecientes: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 259, "cnr_e_58");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 259, "cnr_e_58");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 259, "Vuelo de semicelestial: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 260, "bru_zaf");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 260, "bru_zaf");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 260, "Zafiro en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 261, "bru_zafestre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 261, "bru_zafestre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 261, "Zafiro estrella en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 262, "cnr_zafestre");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 262, "cnr_zafestre");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 262, "Zafiro estrella tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 263, "bru_zafnegro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 263, "bru_zafnegro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 263, "Zafiro negro en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 264, "cnr_zafnegro");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 264, "cnr_zafnegro");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 264, "Zafiro negro tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 265, "cnr_zaf");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 265, "cnr_zaf");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 265, "Zafiro tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 266, "cnr_e_80");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 266, "cnr_e_80");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 266, "Zarpa de can trasguero: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 267, "bru_zen");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 267, "bru_zen");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 267, "Zendalur en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 268, "cnr_zen");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 268, "cnr_zen");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 268, "Zendalur tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 269, "zumoacuoso");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 269, "zumoacuoso");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 269, "Zumos acuosos: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 270, "cnr_e_29");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 270, "cnr_e_29");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 270, "Ímpetu de gigante de la niebla: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 271, "cnr_e_82");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 271, "cnr_e_82");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 271, "Óculo de bocón barbotante: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 272, "bru_opalo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 272, "bru_opalo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 272, "Ópalo común en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 273, "cnr_opalo");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 273, "cnr_opalo");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 273, "Ópalo común tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 274, "bru_opaloa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 274, "bru_opaloa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 274, "Ópalo de agua en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 275, "cnr_opaloa");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 275, "cnr_opaloa");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 275, "Ópalo de agua tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 276, "bru_opalof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 276, "bru_opalof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 276, "Ópalo de fuego en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 277, "cnr_opalof");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 277, "cnr_opalof");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 277, "Ópalo de fuego tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 278, "bru_opalon");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 278, "bru_opalon");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 278, "Ópalo negro en bruto: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 279, "cnr_opalon");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 279, "cnr_opalon");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 279, "Ópalo negro tallado: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 280, "cnr_e_97");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 280, "cnr_e_97");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 280, "Órbita ocular de grimórlock: ");
  SetLocalArrayString(oUbicado, "sTagIngOficio", 281, "cnr_e_83");
  SetLocalArrayString(oUbicado, "sVarIngOficio", 281, "cnr_e_83");
  SetLocalArrayString(oUbicado, "sNomIngOficio", 281, "Órgano sensorial de hongo fantasmal: ");
}
