/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnUsed
void main()
{

object oPC = GetLastUsedBy();

if (!GetIsPC(oPC)) return;

object oTarget;
oTarget = GetObjectByTag("as_cv_gongring3");

SoundObjectSetPosition(oTarget, GetPosition(oPC));

SoundObjectSetVolume(oTarget, 5);

FloatingTextStringOnCreature("* Haces sonar el gong *", oPC);

}
